#!/bin/sh
# Find and run a web browser.

where() { which $1 2>/dev/null; }
browser=`where firefox || where google-chrome || where google-chrome-stable || where opera || where midori || where konqueror || where palemoon`

if [ -e /usr/share/applications/browser.desktop ]; then
	if [ $browser ]; then
		browser=`awk -F= '/Exec=/{print$NF}' /usr/share/applications/browser.desktop | head -n1 | cut -f 1 -d ' ' `
	else
		browser=`awk -F= '/Exec=/{print$NF}' /usr/share/applications/browser.desktop | head -n1`
	fi
fi

$browser $*
