#!/bin/bash

## This script will search for and use an installed text editor.

editors="kwrite kedit kate mousepad leafpad xed tea l3afpad geany pluma featherpad"

if [ `for a in $editors; do command -v $a; done` ]; then
    for a in $editors; do command -v $a >/dev/null && $a $1 && break; done
else 
	xterm -e mcedit $1 && break
fi
