#!/bin/bash
#
# Script to find the graphical su client and use it.

suapps="gksu kdesu ktsuss lxqt-sudo psu"

for a in $suapps; do
    gsu=`command -v $a`
    [ "$gsu" ] && break
done

[ -z "$gsu" ] && { xmessage "No graphical su client found"; exit; }

suclient=${gsu##*/}
case $suclient in
    gksu)
    gksu --message "Please enter the root password." "$@" &
    exit
    ;;
    lxqt-sudo)
    lxqt-sudo "$@" &
    exit
    ;;
    kdesu)
    kdesu -c "$@" &
    exit
    ;;
    psu)
    pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY PATH=/usr/local/sbin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin PORTDIR=$PORTDIR BOOTDEV=$BOOTDEV $@
    exit
    ;;
esac
