#!/bin/bash
#
# Script to find the graphical su client and use it.
if [ "`whoami`" = "root" ]; then
	"$@"
	exit
fi

suapps="gksu kdesu lxqt-sudo psu"

for a in $suapps; do
    gsu=`command -v $a`
    [ "$gsu" ] && break
done

[ -z "$gsu" ] && { xmessage "No graphical su client found"; exit; }

suclient=${gsu##*/}
case $suclient in
    gksu)
    gksu --message "Please enter the root password." "$@" &
    exit
    ;;
    lxqt-sudo)
    lxqt-sudo -s env PORTDIR=$PORTDIR BOOTDEV=$BOOTDEV XDG_DESKTOP_SESSION=$XDG_DESKTOP_SESSION "$@" &
    exit
    ;;
    kdesu)
    kdesu -c "$@" &
    exit
    ;;
    psu)
	if [ -e "/usr/bin/lxpolkit" ] || [ -e "/usr/libexec/polkit-gnome-authentication-agent-1" ]; then
		pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY PATH=/usr/local/sbin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin PORTDIR=$PORTDIR BOOTDEV=$BOOTDEV XDG_DESKTOP_SESSION=$XDG_DESKTOP_SESSION "$@"
	else
		gtk-sudo "$@" &
	fi
    exit
    ;;
esac
