#!/bin/bash
#
# Script to find the graphical su client and use it.

suapps="gksu kdesu ktsuss lxqt-sudo"

for a in $suapps; do
    gsu=`command -v $a`
    [ "$gsu" ] && break
done

[ -z "$gsu" ] && { xmessage "No graphical su client found"; exit; }

suclient=${gsu##*/}
case $suclient in
	gksu)
	gksu --message "Please enter the root password." "$@" &
	exit
	;;
	lxqt-sudo)
	lxqt-sudo "$@" &
	exit
	;;
	kdesu)
	kdesu -c "$@" &
	exit
	;;
esac
