#!/bin/sh
# Script called by rc.S to update various system cache's
# if additional xzm modules were added to the union.

if [ "$1" = rc.S ]; then
    echo "[1m""Additional xzm modules have been found - updating system caches ...""[0m"
else
    echo "[1m""Updating system caches ...""[0m"
fi

# Arch specific variables:
[ `uname -m` = x86_64 ] && lib=lib64 || lib=lib

CACHES=/mnt/live/tmp/caches
mkdir -p $CACHES
if [ $lib = lib64 ]; then
    for y in `ls /mnt/live/memory/images | grep -v "^00"`; do
	    MOD=/mnt/live/memory/images/$y
	    [ -e $MOD/usr/share/applications ] && touch $CACHES/desktop
	    [ -e $MOD/usr/share/mime ] && touch $CACHES/mime
	    [ -e $MOD/usr/share/fonts ] && touch $CACHES/fonts
	    [ -e $MOD/usr/lib64/gtk-2.0/*/immodules ] && touch $CACHES/immodules
	    [ -e $MOD/usr/lib64/gtk-3.0/*/immodules ] && touch $CACHES/immodules
	    [ -e $MOD/usr/share/glib-2.0/schemas ] && touch $CACHES/schemas
	    [ -e $MOD/usr/lib64/gio/modules ] && touch $CACHES/gio
	    [ -e $MOD/etc/ssl/certs ] && touch $CACHES/certs
	    # Multilib support for x86_64 arch:
	    [ -e $MOD/usr/lib/gtk-2.0/*/immodules ] && touch $CACHES/immodules
	    [ -e $MOD/usr/lib/gtk-3.0/*/immodules ] && touch $CACHES/immodules
	    [ -e $MOD/usr/lib/gdk-pixbuf-*/*/loaders ] && touch $CACHES/pixbuf
	    [ -e $MOD/usr/lib/pango/*/modules ] && touch $CACHES/pango
    done
    [ -e $CACHES/pixbuf ] && update-gdk-pixbuf-loaders &
    [ -e $CACHES/pango ] && update-pango-querymodules &
else
    for y in `ls /mnt/live/memory/images | grep -v "^00"`; do
	    MOD=/mnt/live/memory/images/$y
	    [ -e $MOD/usr/share/applications ] && touch $CACHES/desktop
	    [ -e $MOD/usr/share/mime ] && touch $CACHES/mime
	    [ -e $MOD/usr/share/fonts ] && touch $CACHES/fonts
	    [ -e $MOD/usr/lib/gtk-2.0/*/immodules ] && touch $CACHES/immodules
	    [ -e $MOD/usr/lib/gtk-3.0/*/immodules ] && touch $CACHES/immodules
	    [ -e $MOD/usr/share/glib-2.0/schemas ] && touch $CACHES/schemas
	    [ -e $MOD/usr/lib/gio/modules ] && touch $CACHES/gio
	    [ -e $MOD/etc/ssl/certs ] && touch $CACHES/certs
    done
fi

[ -e $CACHES/desktop ] && update-desktop-database &
[ -e $CACHES/mime ] && update-mime-database /usr/share/mime &
[ -e $CACHES/fonts ] && fc-cache -f &
[ -e $CACHES/immodules ] && update-gtk-immodules &
[ -e $CACHES/schemas ] && glib-compile-schemas /usr/share/glib-2.0/schemas &
[ -e $CACHES/gio ] && gio-querymodules /usr/$lib/gio/modules &
[ -e $CACHES/certs ] && update-ca-certificates --fresh &
