#!/bin/sh
# Make sure we get into GUI:

sleep 2
if grep -q 'Fatal server error:' /var/log/Xorg.0.log 2>/dev/null; then
    echo
    if [ -e /etc/X11/xorg.conf ]; then
	if ls /mnt/live/memory/images | egrep -q 'nVidia-|amd-catalyst-|vbox-'; then
	    echo "Xorg failed to start up - deactivating proprietary driver(s)."
	    deactivate `ls /mnt/live/memory/images | egrep 'nVidia-|amd-catalyst-|vbox-'` >/dev/null 2>&1
	    rm -f /etc/X11/xorg.conf
	    if lspci -n | grep -q "0300: 1002:"; then
		modprobe -r fglrx
		modprobe radeon && sleep 1
	    elif lspci -n | grep -q "0300: 10de:"; then
		modprobe -r nvidia
		modprobe nouveau && sleep 1
	    fi
	    killall kdm 2>/dev/null
	else
	    echo "Xorg failed to start up - removing invalid /etc/X11/xorg.conf."
	    rm -f /etc/X11/xorg.conf
	    killall kdm 2>/dev/null
	fi
    else
	if lsmod | grep -qw drm_kms_helper; then
	    echo "Xorg failed to start up - using modesetting driver on next try."
	    cp -af /etc/X11/xorg.conf-modesetting /etc/X11/xorg.conf
	else
	    echo "Xorg failed to start up - using vesa driver on next try."
	    cp -af /etc/X11/xorg.conf-vesa /etc/X11/xorg.conf
	fi
	killall kdm 2>/dev/null
    fi
fi
