#!/bin/bash
# This script is used to provide a GUI messages for 'aufs-remove' script.

. /usr/share/porteus/gtkdialog-functions

BASE=$(basename "$1")
PATH=$PATH:/usr/share/porteus/

# Remove the module from the live filesystem:
/opt/porteus-scripts/xorg/aufs-remove "$BASE"
err=$?

if [ $err -eq 0 ]; then
    gtkdialog.py -p "Well done!" -s "$1: module deactivated." -t 2000
elif [ $err -eq 1 ]; then
    gtkdialog.py -p "$1:" -s "Module is not activated" -d err
elif [ $err -eq 2 ]; then
    gtkdialog.py -p "$1:" -s "Module can't be deactivated. Perhaps some files from the module are still used, opened or executed." -d err
else
    gtkdialog.py -p "$1:" -s "Module can't be deactivated, error $err" -d err
fi

exit $err
