#!/bin/sh
# Update KDE menu:

echo "Updating KDE menu: update-desktop-database"
for x in `ps -C startkde -o user=`; do echo "Updating menu"; kbuildsycoca4; kbuildsycoca5; done
update-desktop-database
xdg-desktop-menu forceupdate
