#!/bin/sh
# KDE startup helper.

# Show notification for errors with changes cheatcode
REASON_1="A Windows filesystem (FAT, NTFS) or other non-posix compatible filesystem has been detected on your changes location.
Your changes cannot be saved directly to the specified storage media with this setup. Please use the Porteus save file manager application to create a .dat container and use it for saving your changes after your next reboot."

REASON_2="The changes location is not writable. This may be because the changes path is located on a read-only filesystem."

REASON_3="The changes location as provided in the changes cheatcode could not be found."

if [ "$CHGERR" ]; then
  case "$CHGERR" in
    1) REASON="$REASON_1"          
       ;;
    2) REASON="$REASON_2"          
       ;;
    3) REASON="$REASON_3"
       ;;
  esac
  echo "$REASON" > "/tmp/chg_errlog"
  notify-send -t 0 -u critical -i dialog-error "Changes are not saved" "More information here: /tmp/chg_errlog"
fi

