.TH LSDEV 8 "1998-05-31" "3rd Release" "Linux System Manual"

.SH NAME
lsdev \- display information about installed hardware

.SH SYNOPSIS
.B lsdev

.SH DESCRIPTION
.B lsdev
gathers information about your computer's installed hardware from the
.B interrupts,
.B ioports
and
.B dma
files in the
.B /proc
directory, thus giving you a quick overview of which hardware uses
what I/O addresses and what IRQ and DMA channels.

.SH OPTIONS
None.

.SH FILES
.TP
.BI /proc/interrupts
IRQ channels.

.TP
.BI /proc/ioports
I/O memory addresses.

.TP
.BI /proc/dma
DMA channels.

.SH BUGS
.B lsdev
can't always figure out which lines in the three examined files refer
to one and the same device, because these files sometimes use
different names for the same piece of hardware. For example, in some
kernels the keyboard is referred to as `kbd' in
.B /proc/ioports
and as `keyboard' in
.B /proc/interrupts.
This should be fixed in the kernel, not in 
.B lsdev
(as has indeed happened for this particular example).

The program does however try to match lines by stripping anything
after a space or open parenthesis from the name, so that e.g. the
`serial' lines from 
.B /proc/interrupts
match the `serial(set)' lines from
.B /proc/ioports.
This attempt at DWIM might be considered a bug in itself.

This program only shows the kernel's 
.BI idea
of what hardware is present, not what's actually physically available.

.SH SEE ALSO
procinfo(8).

.SH AUTHOR
Sander van Malssen <svm@kozmix.cistron.nl>
