.TH SOCKLIST 8 "1998-02-09" "1st Release" "Linux System Manual"

.SH NAME
socklist \- display list of open sockets

.SH SYNOPSIS
.B socklist

.SH DESCRIPTION

.B socklist
is a Perl script that gives you a list of all open sockets,
enumerating types, port, inode, uid, pid, fd and the program to which
it belongs.

.SH OPTIONS
None.

.SH FILES
.TP
.BI /proc/*/fd/*
File descriptors.

.TP
.BI /proc/net/tcp
List of TCP sockets.

.TP
.BI /proc/net/udp
List of UDP sockets.

.TP
.BI /proc/net/raw
List of raw sockets.

.SH BUGS
None as yet.

.SH SEE ALSO
procinfo(8), netstat(8).

.SH AUTHOR
Larry Doolittle <ldoolitt@jlab.org>
