'\" t
.\"     Title: dconf-service
.\"    Author: Ryan Lortie <desrt@desrt.ca>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 08/17/2014
.\"    Manual: User Commands
.\"    Source: dconf
.\"  Language: English
.\"
.TH "DCONF\-SERVICE" "1" "" "dconf" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dconf-service \- D\-Bus service for writes to the dconf database
.SH "SYNOPSIS"
.HP \w'\fBdconf\-service\fR\ 'u
\fBdconf\-service\fR
.SH "DESCRIPTION"
.PP
The
\fBdconf\-service\fR
program provides the
\fIca\&.desrt\&.dconf\fR
name on the session or system bus\&. Users or administrators should never need to start the service, as it will be automatically started by
\fBdbus-daemon\fR(1)
whenever an application tries to write settings\&.
.PP
Reading values from the dconf database does not involve the service; it is only needed for writes\&. The service is stateless and can exit freely at any time (and is therefore robust against crashes)\&.
.SH "SEE ALSO"
.PP
\fBdconf\fR(7),
\fBdbus-daemon\fR(1),
\fBsystemd\fR(1)
