#!/usr/bin/python
## encrypt script in pygobject3

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import subprocess
import tempfile
import os

class GtkEncrypt(Gtk.Window):
    def __init__(self):
        Gtk.Window.__init__(self, title = "Encrypt", border_width = 15, height_request = 300, width_request = 450, icon_name = "channel-secure-symbolic")
        self.vb = Gtk.Box(spacing = 5, orientation = Gtk.Orientation.VERTICAL)

        self.l_header_txt = Gtk.Label()
        self.l_header_txt.set_markup("<span size=\"x-large\" weight=\"bold\">Encrypt a file or folder</span>")
        self.vb.pack_start(self.l_header_txt, False, False, 5)

        self.vb.pack_start(Gtk.Separator(), False, False, 5)

        self.text = Gtk.Label()
        self.text.set_markup("<span>Your chosen file/folder will be encrypted and the original\n then removed from the system. If a folder is chosen it will\n be converted into a single encrypted file which will need to\n be decrypted using this application. DO NOT forget your\n password or you will lose you data!</span>")
        self.vb.add(self.text)

        self.vb.pack_start(Gtk.Separator(), False, False, 10)
        
        self.hb1 = Gtk.Box(spacing = 5, homogeneous = False)
        self.hb1.pack_start(Gtk.Label(label = "Folder: "), False, False, 5)
        self.entry = Gtk.Entry()
        self.hb1.pack_start(self.entry, False, False, 5)
        self.add_folder_button = Gtk.Button.new_from_icon_name("folder-new-symbolic", Gtk.IconSize.BUTTON)
        self.add_folder_button.connect("clicked", self.on_add_folder_button_clicked)        
        self.hb1.pack_start(self.add_folder_button, False, False, 5)                
        self.vb.add(self.hb1)        
                
        self.hb2 = Gtk.Box(spacing = 5, homogeneous = False)
        self.hb2.pack_start(Gtk.Label(label = "File:      "), False, False, 5)
        self.entry2 = Gtk.Entry()
        self.hb2.pack_start(self.entry2, False, False, 5)
        self.add_file_button = Gtk.Button.new_from_icon_name("text-x-generic-symbolic", Gtk.IconSize.BUTTON)
        self.add_file_button.connect("clicked", self.on_add_file_button_clicked)
        self.hb2.pack_start(self.add_file_button, False, False, 5)       
        self.vb.add(self.hb2)        
         
        self.hb_bottom = Gtk.Box(spacing = 5, homogeneous = False)
        self.cancel_button = Gtk.Button.new_with_label("Cancel")
        self.cancel_button.connect("clicked", self.on_cancel_clicked)
        self.hb_bottom.pack_end(self.cancel_button, False, False, 2)
        
        self.ok_button = Gtk.Button.new_with_label("OK")
        self.ok_button.connect("clicked", self.on_ok_clicked)
        # ~ self.ok_button.set_sensitive(False)
        self.hb_bottom.pack_end(self.ok_button, False, False, 2)        

        self.vb.pack_end(self.hb_bottom, False, False, 5)
        self.vb.pack_end(Gtk.Separator(), False, False, 10)
        self.add(self.vb)

    def on_add_folder_button_clicked(self, button):
        dialog = Gtk.FileChooserDialog(title = "Choose a folder to encrypt", parent = self,
            action = Gtk.FileChooserAction.SELECT_FOLDER)
        dialog.add_buttons(Gtk.STOCK_CANCEL, Gtk.ResponseType.CANCEL,
             "Select", Gtk.ResponseType.OK)
        dialog.set_default_size(800, 400)

        response = dialog.run()
        if Gtk.ResponseType.OK == response:
            # ~ self.add_folder_path(dialog.get_filename())
            print("fixme")

        dialog.destroy()        
        
    def on_add_file_button_clicked(self, button):
        dialog = Gtk.FileChooserDialog(title = "Choose a file to encrypt", parent = self,
            action = Gtk.FileChooserAction.OPEN)
        dialog.add_buttons(Gtk.STOCK_CANCEL, Gtk.ResponseType.CANCEL,
             "Select", Gtk.ResponseType.OK)
        dialog.set_default_size(800, 400)

        response = dialog.run()
        if Gtk.ResponseType.OK == response:
            # ~ self.add_file_path(dialog.get_filename())
            print("fixme")

        dialog.destroy()

    def on_ok_clicked(self, button):
        # Dummy
        # ~ subprocess.Popen(['encrypt command'], %s)
        dialog = Gtk.MessageDialog(parent = self, flags = 0, message_type = Gtk.MessageType.INFO, buttons = Gtk.ButtonsType.OK, text = "Encrypt")
        dialog.format_secondary_text("Your file has been encrypted")
        dialog.run()
        dialog.destroy()
        Gtk.main_quit()

    def on_cancel_clicked(self, button):
        Gtk.main_quit()

win = GtkEncrypt()
win.connect("destroy", Gtk.main_quit)
win.show_all()
Gtk.main()
