#!/usr/bin/python
## firewall script in pygobject3

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import subprocess
import tempfile
import os
import platform

class GtkFireW(Gtk.Window):

    def __init__(self):
        Gtk.Window.__init__(self, title = "Firewall", border_width = 15, height_request = 300, width_request = 450, icon_name = "security-high-symbolic")
        self.vb = Gtk.Box(spacing = 5, orientation = Gtk.Orientation.VERTICAL)

        self.l_header_txt = Gtk.Label()
        self.l_header_txt.set_markup("<span size=\"x-large\" weight=\"bold\">Porteus Firewall Manager</span>")
        self.vb.pack_start(self.l_header_txt, False, False, 5)

        self.vb.pack_start(Gtk.Separator(), False, False, 5)

        self.text = Gtk.Label()
        self.text.set_markup("<span>Use the options below to toggle your firewall on/off and set the desired\n security levels.These actions take place in real time. Setting the firewall\n to activate during boot will take place the next time you boot Porteus.</span>")
        self.vb.add(self.text)

        self.vb.pack_start(Gtk.Separator(), False, False, 10)

        self.checkbox = Gtk.CheckButton.new_with_label("Activate firewall when Porteus starts")
        self.checkbox.connect("toggled", self.on_checkbox_checked)
        check = os.access('/etc/rc.d/rc.FireWall', os.X_OK)
        if check:
            self.checkbox.set_active(True)
        else:
            self.checkbox.set_active(False)
        self.vb.add(self.checkbox)

        self.vb.pack_start(Gtk.Separator(), False, False, 10)

        self.hb = Gtk.Box(spacing = 5, orientation = Gtk.Orientation.HORIZONTAL)

        self.button1 = Gtk.Button.new_with_label("Information")
        self.button1.connect("clicked", self.on_button1_clicked)
        self.hb.add(self.button1)

        self.button2 = Gtk.Button.new_with_label("Blockall")
        self.button2.connect("clicked", self.on_button2_clicked)
        self.hb.add(self.button2)

        self.button3 = Gtk.Button.new_with_label("Strict")
        self.button3.connect("clicked", self.on_button3_clicked)
        self.hb.add(self.button3)

        self.button4 = Gtk.Button.new_with_label("Normal")
        self.button4.connect("clicked", self.on_button4_clicked)
        self.hb.add(self.button4)

        self.button5 = Gtk.ToggleButton.new_with_label("Toggle Firewall")
        self.button5.connect("toggled", self.on_button5_toggled, "TF")
        p1 = subprocess.Popen(['sh', '/etc/rc.d/rc.FireWall', 'status'], stdout=subprocess.PIPE)
        p2 = subprocess.Popen(['grep', '-o', 'LOG_DROP'], stdin=p1.stdout, stdout=subprocess.PIPE)
        p3 = subprocess.run(['head', '--lines=1'], stdin=p2.stdout, stdout=subprocess.PIPE).stdout.decode('utf-8')
        if p3:
            self.button5.set_active(True)
        else:
            self.button5.set_active(False)
        self.hb.add(self.button5)

        self.vb.add(self.hb)

        self.hb_bottom = Gtk.Box(spacing = 5, homogeneous = False)
        self.cancel_button = Gtk.Button.new_with_label("Exit")
        self.cancel_button.connect("clicked", self.on_cancel_clicked)
        self.hb_bottom.pack_end(self.cancel_button, False, False, 2)
        self.vb.pack_end(self.hb_bottom, False, False, 5)
        self.vb.pack_end(Gtk.Separator(), False, False, 10)
        self.status_bar = Gtk.Statusbar.new()
        if p3:
            self.status_bar_on()
        else:
            self.status_bar_off()
        self.vb.pack_end(self.status_bar, False, False, 5)
        self.add(self.vb)

    def status_bar_on(self):
        status_bar = Gtk.Statusbar.new()
        status_bar.remove_all(1)
        self.status_bar.push(1, "FIREWALL STATUS: ON")

    def status_bar_off(self):
        status_bar = Gtk.Statusbar.new()
        status_bar.remove_all(1)
        self.status_bar.push(1, "FIREWALL STATUS: OFF")

    def on_checkbox_checked(self, checkbox):
        if checkbox.get_active():
            os.chmod('/etc/rc.d/rc.FireWall', 0o755)
            state = "on"
        else:
            os.chmod('/etc/rc.d/rc.FireWall', 0o644)
            state = "off"
        print("checkbox was turned", state)

    def on_button1_clicked(self, button):
        self.tmp_dir = tempfile.TemporaryDirectory()
        #print('created temporary directory', self.tmp_dir.name)
        outfile = self.tmp_dir.name + "/fwinfo.txt"
        with open(outfile, "w") as f:
            subprocess.Popen(['sh', '/etc/rc.d/rc.FireWall', 'status'], stdout = f)
        with open(outfile, "r") as f:
            subprocess.Popen(['/opt/porteus-scripts/xorg/editor', outfile])

    def on_button2_clicked(self, button):
        print("fixme")

    def on_button3_clicked(self, button):
        print("fixme")

    def on_button4_clicked(self, button):
        print("fixme")

    def on_button5_toggled(self, button, name):
        # ~ print("fixme")
        if button.get_active():
            state = "on"
            subprocess.run(['sh', '/etc/rc.d/rc.FireWall', 'start'])
            self.status_bar_on()
        else:
            state = "off"
            subprocess.run(['sh', '/etc/rc.d/rc.FireWall', 'stop'])
            self.status_bar_off()
        print("Button", name, "was turned", state)

    def on_cancel_clicked(self, button):
        Gtk.main_quit()

win = GtkFireW()
win.connect("destroy", Gtk.main_quit)
win.show_all()
Gtk.main()
