#!/usr/bin/python
#
# Author: jssouza
#
# This is a script to download a live script and update Porteus

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('Vte', '2.91')

from gi.repository import Gtk, Vte, Gdk, GLib, Gio
import os

class MainWindow(Gtk.Window):

    def __init__(self):
        Gtk.Window.__init__(self, title = "Porteus Updater", border_width = 5, height_request = 500, width_request = 550, icon_name = "system-settings")

        self.vb = Gtk.Box(spacing = 5, orientation = Gtk.Orientation.VERTICAL)
        self.vb.set_homogeneous(False)

        self.l_header_txt = Gtk.Label()
        self.l_header_txt.set_markup("<span size=\"x-large\" weight=\"bold\">Performing Porteus update check</span>")
        self.l_header_txt.set_justify(Gtk.Justification.CENTER)

        self.vb.pack_start(self.l_header_txt, False, False, 5)

        terminal = Vte.Terminal()
        pty = Vte.Pty.new_sync(Vte.PtyFlags.DEFAULT)
        terminal.set_pty(pty)
        pty.spawn_async(None, ["/opt/porteus-scripts/update-porteus"], None, GLib.SpawnFlags.DO_NOT_REAP_CHILD, None, None, -1, None, self.ready)

        scrolledwindow = Gtk.ScrolledWindow()
        scrolledwindow.add(terminal)

        self.vb.pack_start(scrolledwindow, True, True, 0)

        self.hb_bottom = Gtk.Box(spacing = 5)
        self.hb_bottom.set_homogeneous(False)
        self.ok_button = Gtk.Button.new_with_label("OK")
        self.ok_button.connect("clicked", self.on_ok_button_clicked)
        self.hb_bottom.pack_end(self.ok_button, False, False, 6)

        self.vb.pack_start(self.hb_bottom, False, False, 6)
        self.add(self.vb)


    def ready(self, pty, task):
        # print('ready')
        None

    def on_ok_button_clicked(self, button):
        Gtk.main_quit()


win = MainWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
