#!/bin/bash

# Copyright 2016-2020  Jay Flood, SP, Brasil
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Author: brokenman@porteus.org
#
# This is a script to download a live script and update Porteus

# Source some functions
. /usr/share/porteus/porteus-functions
. /usr/share/porteus/gtkdialog-functions

SCRIPT="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"

echo '
<window title="Porteus updater" icon="system-settings">
<vbox>
<hbox>
      <pixmap icon_size="5">
        <input file stock="gtk-about"></input>
      </pixmap>
	'`txtcolor 400 darkred x-large normal "  Performing Porteus update check"`'
	'`hsep`'
</hbox>
	<frame>
		<terminal argv0="/bin/sh"
		envv0="WELCOME=Welcome to the Porteus update procedure"
		pointer-autohide="false"
		hscrollbar-policy="2"
		vscrollbar-policy="2">
		<variable>vte1</variable>
		<input>echo "sh /opt/porteus-scripts/update-porteus"</input>
		</terminal>
	</frame>
<hbox>
	'`butok`'
</hbox>
</vbox>
</window>
'|gtkdialog -s
