#!/usr/bin/python
#
# Author: jssouza
#
# This is a script to download a live script and update Porteus

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, Gdk, GLib, Gio
import os
import sys

class MainWindow(Gtk.Window):

    def __init__(self):
        Gtk.Window.__init__(self, title = "Pass", border_width = 5, height_request = 150, width_request = 350, icon_name = "security-high", window_position = 1, type = 0)

        self.vb = Gtk.Box(spacing = 5, orientation = Gtk.Orientation.VERTICAL)
        self.vb.set_homogeneous(False)

        self.l_header_txt = Gtk.Label()
        self.l_header_txt.set_markup("<span size=\"x-large\" weight=\"bold\">Please enter Root password</span>")
        self.l_header_txt.set_justify(Gtk.Justification.CENTER)
        self.vb.pack_start(self.l_header_txt, False, False, 5)

        self.entry = Gtk.Entry()
        self.entry.set_visibility(0)
        # ~ self.entry.set_activates_default(True)
        # ~ self.entry.get_activates_default()
        self.vb.pack_start(self.entry, True, True, 0)

        self.hb_bottom = Gtk.Box(spacing = 5)
        self.hb_bottom.set_homogeneous(False)
        
        self.ok_button = Gtk.Button.new_with_label("OK")
        self.ok_button.connect("clicked", self.on_ok_button_clicked)
        self.hb_bottom.pack_end(self.ok_button, False, False, 6)
        
        self.cancel_button = Gtk.Button.new_with_label("Cancel")
        self.cancel_button.connect("clicked", self.on_cancel_button_clicked)
        self.hb_bottom.pack_end(self.cancel_button, False, False, 6)

        self.vb.pack_start(self.hb_bottom, False, False, 6)
        self.add(self.vb)

    def on_ok_button_clicked(self, button):
        self.text = Gtk.Entry.get_text(self.entry)
        try:
            target1 = sys.argv[1]
            target2 = sys.argv[2]
            os.system("echo " + self.text + " | sudo -S " + target1 + " " + target2 + "&")
        except IndexError:
            os.system("echo " + self.text + " | sudo -S " + target1 + "&")
        Gtk.main_quit()
        
    def on_cancel_button_clicked(self, button):
        Gtk.main_quit()


win = MainWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
