#!/bin/sh
# Convert .rpm package to .xzm module.

# Variables
c='\e[36m'
r='\e[31m'
e=`tput sgr0`

. /usr/share/porteus/porteus-functions
. /usr/share/porteus/gtkdialog-functions
get_colors
function chklibs(){
echo "Checking required libraries ..."
echo
if [[ ! `ldconfig -p | grep libbfd` ]]; then
	bold "#############################"
	bold "#     Missing library       #"
	bold "#############################"
	echo
	echo "You are missing libbfd. Please"
	echo "activate 05_devel or run the"
	bold "command: getpkg binutils"
	echo "and installpkg the file."
	echo
	exit
fi	
}

show_help() {
    echo
    echo "Convert Red Hat's RPM package into .xzm compressed module"
    echo "usage: $0 <option> <argument> "
    echo " options:  -x : use xz compression. "
    echo " options:  -z : use zstd compression. "
    echo " if no option is given xz is used. "
    echo "           -h       : show this usage. "
    echo
    echo "example: $0 /mnt/sda2/fedora_packages/package.rpm"
	echo
}

COMP="-x"
COMP_ZSTD="-z"

while getopts "xzh" opt; do
case "$opt" in

    x)
        shift "$(($OPTIND -1))"
        ;;

    z)
        COMP="$COMP_ZSTD"
        shift "$(($OPTIND -1))"
        ;;
  
    h)
        show_help
        exit 0
        ;;
    
esac
done

if [ "$1" = "" ]; then
    show_help
    exit 1
fi

# Work only on rpm packages:
for x in $*; do
    ext=`echo $x | rev | cut -d. -f1 | rev`
    if [ "$ext" = rpm ]; then
        mod=`readlink -f $x`
        MOD=`echo $MOD $mod`
    fi
done

# Switch to root
if [ "$DISPLAY" ]; then
   if [ `whoami` != "root" ]; then
      /opt/porteus-scripts/xorg/psu /opt/porteus-scripts/rpm2xzm $COMP $MOD
      exit
   fi
else
   if [ `whoami` != "root" ]; then
      echo "Please enter root's password below"
      su -c "/opt/porteus-scripts/rpm2xzm $COMP $MOD"
      exit
   fi
fi

# Create module:
for y in $MOD; do
    mod=`readlink -f $y | sed s/.rpm$/.xzm/`
    pkg=`echo $mod | awk -F/ '{print$NF}' | sed s/.xzm//g`
    if [ "$DISPLAY" ]; then
	mkdir /tmp/rpm2xzm$$ && cp $y /tmp/rpm2xzm$$ && cd /tmp/rpm2xzm$$ && rpm2txz $pkg.rpm && txz2xzm $COMP $pkg.txz && mv $pkg.xzm $mod
	if [ $? -eq 0 ]; then
	    gtkdialog.py -p "Success! Module created as $mod" -t 2000
	else
	    gtkdialog.py -p "Error , $mod creation failed." -d err
	fi
    else
	mkdir /tmp/rpm2xzm$$ && cp $y /tmp/rpm2xzm$$ && cd /tmp/rpm2xzm$$ && rpm2txz $pkg.rpm && txz2xzm $pkg.txz && mv $pkg.xzm $mod && echo -e "${c}Module created as $mod"$e || echo -e ''${r}$mod' creation failed!'$e
    fi
    rm -rf /tmp/rpm2xzm$$
done
