#!/bin/bash

# Script to update porteus to the latest version and create
# a slackware package. This script downloads a live script
# from the porteus server so it can be updated real time to
# accomodate any changes mozilla might make.

SERVER=`awk -F= '/SERVER=/{print$NF}' /etc/porteus.conf`
LIVESCRIPT="$SERVER/i586/testing/live/update-firefox-live"

txtbld=$(tput bold)
txtred=${txtbld}$(tput setaf 1)
txtgreen=${txtbld}$(tput setaf 2)
txtwhite=${txtbld}$(tput setaf 7)
txtcyan=${txtbld}$(tput setaf 6)
rst=$(tput sgr0)
function bold(){ echo -e $txtbld "$1" $rst; }
function green() { echo -e $txtgreen "$1" $rst; }
function red(){ echo $txtred "$1" $rst; }	
function cyan(){ echo $txtcyan "$1" $rst; }

is_online_url(){ ( wget -q --spider --force-html --inet4-only $1 >/dev/null 2>&1 ); }

download() {
local url=$1
local file=${url##*/}

dloadInProgress=$url

echo -n "Downloading: $file --> "
wget $url -P $2 2>&1 | grep --line-buffered "%" |sed -u -e "s,\.,,g" | awk '{printf("\b\b\b\b%4s", $2)}'
echo -ne "\b\b\b\b"
echo " DONE"
unset dloadInProgress
}

# Root check
if [ `whoami` != "root" ]; then
	echo
	red "Only root can run this."
	exit
fi

## Check we have internet
echo "Checking internet ..."
is_online_url http://dl.porteus.org || { echo "Fatal error. Could not contact server."; exit 1; }

download $LIVESCRIPT /tmp || { red "Failed to download live script."; exit 1; }
chmod +x /tmp/update-firefox-live
mv /tmp/update-firefox-live /usr/local/bin
/usr/local/bin/update-firefox-live
exit
