#!/bin/sh
# Convert .deb. packages to .xzm modules.

# Variables
c='\e[36m'
r='\e[31m'
e=`tput sgr0`

. /usr/share/porteus/porteus-functions
get_colors
function chklibs(){
echo "Checking required libraries ..."
echo
if [[ ! `ldconfig -p | grep libbfd` ]]; then
	bold "#############################"
	bold "#     Missing library       #"
	bold "#############################"
	echo
	echo "You are missing libbfd. Please"
	echo "activate 05_devel or run the"
	bold "command: getpkg binutils"
	echo "and installpkg the file."
	echo
	exit
fi
}

# Let's start
chklibs
if [ "$1" = "" ]; then
    echo -e "${c}nead a deb package as an argument, example: $0 /mnt/sda2/debian_packages/package.deb"$e | fmt -w 80
    exit
fi

# Work only on deb packages:
for x in $*; do
    ext=`echo $x | rev | cut -d. -f1 | rev`
    if [ "$ext" = deb ]; then
        mod=`readlink -f $x`
        MOD=`echo $MOD $mod`
    fi
done

# Switch to root
if [ "$DISPLAY" ]; then
   if [ `whoami` != "root" ]; then
      /opt/porteus-scripts/xorg/psu "/opt/porteus-scripts/deb2xzm $MOD"
      exit
   fi
else
   if [ `whoami` != "root" ]; then
      echo "Please enter root's password below"
      su -c "/opt/porteus-scripts/deb2xzm $MOD"
      exit
   fi
fi

# Create module:
for y in $MOD; do
    mod=`readlink -f $y | sed s/.deb$/.xzm/`
    pkg=`echo $mod | awk -F/ '{print$NF}' | sed s/.xzm//g`
    dataname=`ar t $y | grep data`
    if [ "$DISPLAY" ]; then
	case $dataname in
	data.tar.bz2)
	mkdir /tmp/deb2xzm$$ && cp $y /tmp/deb2xzm$$ && cd /tmp/deb2xzm$$ && /usr/bin/ar x * data.tar.gz && bzip2 -d data.tar.bz2 && gzip data.tar && mv data.tar.gz $pkg.tgz && txz2xzm /tmp/deb2xzm$$/$pkg.tgz && mv /tmp/deb2xzm$$/$pkg.xzm $mod
	if [ $? -eq 0 ]; then
	    Xdialog --title "success" --no-close --no-buttons --infobox "Module created as $mod" 0 0 2000 &
	else
	    Xdialog --title "error" --msgbox "$mod creation failed!" 0 0 &
	fi
	;;
	data.tar.gz)
	mkdir /tmp/deb2xzm$$ && cp $y /tmp/deb2xzm$$ && cd /tmp/deb2xzm$$ && /usr/bin/ar x * data.tar.gz && mv data.tar.gz $pkg.tgz && txz2xzm /tmp/deb2xzm$$/$pkg.tgz && mv /tmp/deb2xzm$$/$pkg.xzm $mod
	if [ $? -eq 0 ]; then
	    Xdialog --title "success" --no-close --no-buttons --infobox "Module created as $mod" 0 0 2000 &
	else
	    Xdialog --title "error" --msgbox "$mod creation failed!" 0 0 &
	fi
	;;
	data.tar.lzma)
	mkdir /tmp/deb2xzm$$ && cp $y /tmp/deb2xzm$$ && cd /tmp/deb2xzm$$ && /usr/bin/ar x * data.tar.lzma && unxz data.tar.lzma && gzip data.tar && mv data.tar.gz $pkg.tgz && txz2xzm /tmp/deb2xzm$$/$pkg.tgz && mv /tmp/deb2xzm$$/$pkg.xzm $mod
	if [ $? -eq 0 ]; then
	    Xdialog --title "success" --no-close --no-buttons --infobox "Module created as $mod" 0 0 2000 &
	else
	    Xdialog --title "error" --msgbox "$mod creation failed!" 0 0 &
	fi
	;;
	data.tar.xz)
	mkdir /tmp/deb2xzm$$ && cp $y /tmp/deb2xzm$$ && cd /tmp/deb2xzm$$ && /usr/bin/ar x * data.tar.xz && unxz data.tar.xz && gzip data.tar && mv data.tar.gz $pkg.tgz && txz2xzm /tmp/deb2xzm$$/$pkg.tgz && mv /tmp/deb2xzm$$/$pkg.xzm $mod
	if [ $? -eq 0 ]; then
	    Xdialog --title "success" --no-close --no-buttons --infobox "Module created as $mod" 0 0 2000 &
	else
	    Xdialog --title "error" --msgbox "$mod creation failed!" 0 0 &
	fi
	;;
	esac
    else
	case $dataname in
	data.tar.bz2)
	mkdir /tmp/deb2xzm$$ && cp $y /tmp/deb2xzm$$ && cd /tmp/deb2xzm$$ && /usr/bin/ar x * data.tar.gz && bzip2 -d data.tar.bz2 && gzip data.tar && mv data.tar.gz $pkg.tgz && txz2xzm /tmp/deb2xzm$$/$pkg.tgz && mv /tmp/deb2xzm$$/$pkg.xzm $mod && echo && echo -e "${c}Module created as $mod"$e || echo -e ''${r}$mod' creation failed!'$e
	;;
	data.tar.gz)
	mkdir /tmp/deb2xzm$$ && cp $y /tmp/deb2xzm$$ && cd /tmp/deb2xzm$$ && /usr/bin/ar x * data.tar.gz && mv data.tar.gz $pkg.tgz && txz2xzm /tmp/deb2xzm$$/$pkg.tgz && mv /tmp/deb2xzm$$/$pkg.xzm $mod && echo && echo -e "${c}Module created as $mod"$e || echo -e ''${r}$mod' creation failed!'$e
	;;
	data.tar.lzma)
	mkdir /tmp/deb2xzm$$ && cp $y /tmp/deb2xzm$$ && cd /tmp/deb2xzm$$ && /usr/bin/ar x * data.tar.lzma && unxz data.tar.lzma && gzip data.tar && mv data.tar.gz $pkg.tgz && txz2xzm /tmp/deb2xzm$$/$pkg.tgz && mv /tmp/deb2xzm$$/$pkg.xzm $mod && echo && echo -e "${c}Module created as $mod"$e || echo -e ''${r}$mod' creation failed!'$e
	;;
	data.tar.xz)
	mkdir /tmp/deb2xzm$$ && cp $y /tmp/deb2xzm$$ && cd /tmp/deb2xzm$$ && /usr/bin/ar x * data.tar.xz && unxz data.tar.xz && gzip data.tar && mv data.tar.gz $pkg.tgz && txz2xzm /tmp/deb2xzm$$/$pkg.tgz && mv /tmp/deb2xzm$$/$pkg.xzm $mod && echo && echo -e "${c}Module created as $mod"$e || echo -e ''${r}$mod' creation failed!'$e
	;;
	esac
    fi
    rm -rf /tmp/deb2xzm$$
done
