#!/bin/bash
# A script to scrape the system and output
# a text file on the desktop with sysinfo

# Switch to root:
if [ `whoami` != "root" ]; then
    echo "Please enter root's password below"
    su - -c "/opt/porteus-scripts/psinfo `whoami`" || sleep 1
    exit
fi

# Set output:
info=/tmp/psinfo.txt

# Collect data:
echo "PORTEUS VERSION:" > $info
cat /etc/porteus-version >> $info
echo "" >> $info
echo "KERNEL/PROCESSOR:" >> $info
echo `uname -r` `uname -m` `uname -p`>> $info
echo "" >> $info
echo "MEMORY/SWAP:" >> $info
free -m >> $info
echo "" >> $info
echo "BLOCK DEVICES:" >> $info
ls -1 /sys/block | grep -v loop | sed s/@// >> $info
echo "" >> $info
echo "PARTITIONS:" >> $info
blkid | grep -v squashfs >> $info
echo "" >> $info
echo "MOUNTED PARITIONS:" >> $info
df -Th | grep -v devtmpfs >> $info
echo "" >> $info
echo "CHEATCODES:" >> $info
cat /etc/bootcmd.cfg >> $info
echo "" >> $info
echo "LIVEDBG INFO:" >> $info
cat /var/log/porteus-livedbg >> $info
echo "" >> $info
echo "SOUND CARDS:" >> $info
cat /proc/asound/cards >> $info
echo "" >> $info
echo "LSPCI OUTPUT:" >> $info
lspci -knn >> $info
echo "" >> $info
echo "LSUSB OUTPUT:" >> $info
lsusb -t >> $info
echo "" >> $info
echo "LSMOD OUTPUT:" >> $info
lsmod >> $info
echo "" >> $info
echo "BATTERY INFO:" >> $info
dmidecode -t 22|sed -e '/dmidecode/d' -e '/SMBIOS/d' -e '/Handle/d' -e '/^$/d' >> $info
echo "" >> $info
echo "CHASSIS INFO:" >> $info
dmidecode -t 3|sed -e '/dmidecode/d' -e '/SMBIOS/d' -e '/Handle/d' -e '/^$/d' >> $info
echo "" >> $info
echo "SYSTEM INFO:" >> $info
dmidecode -t 1|sed -e '/dmidecode/d' -e '/SMBIOS/d' -e '/Handle/d' -e '/^$/d'  >> $info
echo "" >> $info
echo "USER INFO:" >> $info
grep -v "\!" /etc/shadow|cut -d':' -f1 >> $info
echo "" >> $info
echo "LAST BOOT:" >> $info
who -b|sed 's/^[ \t]*//' >> $info
echo "Uptime (hr:min) : `uptime|awk '{print$3}'|sed 's/,//g'`" >> $info
echo "" >> $info
echo "LOADED MODULES:" >> $info
ls -1 /mnt/live/memory/images >> $info
echo "" >> $info
echo "LOADED PACKAGES:" >> $info
ls -1 /var/log/packages >> $info
echo "" >> $info
echo "/var/log/messages:" >> $info
tac /var/log/messages | sed -n '1,/kmsg started./p' | tac  >> $info
if [ "$DISPLAY" ]; then
    echo "" >> $info
    echo "SCREEN:" >> $info
    xrandr >> $info
    echo "" >> $info
    echo "OpenGL version:" >> $info
    glxinfo | grep OpenGL >> $info
    echo "" >> $info
    echo "/var/log/Xorg.0.log:" >> $info
    cat /var/log/Xorg.0.log >> $info
    echo "" >> $info
    echo "XSESSION ERRORS:" >> $info
    [ -f /root/.xsession-errors ] && echo "USER: root" >> $info && cat /root/.xsession-errors >> $info
    for a in `grep -v "\!" /etc/shadow|cut -d':' -f1|sed 'root/d'`; do
	[ -f /home/$a/.xsession-errors ] && echo "USER: $a" >> $info && cat /home/$a/.xsession-errors >> $info
    done
fi
echo
echo "All gathered information are stored in [1;33m$info[0m"
echo -e "If you want the Team Porteus to trouble shooting a problem then please upload\nthis file to pastebin.com and post a link in our forums."

exit
