#!/bin/sh
# Convert .rpm package to .xzm module.

# Variables
c='\e[36m'
r='\e[31m'
e=`tput sgr0`

# Let's start
if [ "$1" = "" ]; then
    echo -e "${c}need a rpm package as an argument, example: $0 /mnt/sda2/fedora_packages/package.rpm"$e | fmt -w 80
    exit
fi

# Work only on rpm packages:
for x in $*; do
    ext=`echo $x | rev | cut -d. -f1 | rev`
    if [ "$ext" = rpm ]; then
        mod=`readlink -f $x`
        MOD=`echo $MOD $mod`
    fi
done

# Switch to root
if [ "$DISPLAY" ]; then
   if [ `whoami` != "root" ]; then
      /opt/porteus-scripts/xorg/psu "/opt/porteus-scripts/rpm2xzm $MOD"
      exit
   fi
else
   if [ `whoami` != "root" ]; then
      echo "Please enter root's password below"
      su -c "/opt/porteus-scripts/rpm2xzm $MOD"
      exit
   fi
fi

# Create module:
for y in $MOD; do
    mod=`readlink -f $y | sed s/.rpm$/.xzm/`
    pkg=`echo $mod | awk -F/ '{print$NF}' | sed s/.xzm//g`
    if [ "$DISPLAY" ]; then
	mkdir /tmp/rpm2xzm$$ && cp $y /tmp/rpm2xzm$$ && cd /tmp/rpm2xzm$$ && rpm2txz $pkg.rpm && txz2xzm $pkg.txz && mv $pkg.xzm $mod
	if [ $? -eq 0 ]; then
	    Xdialog --title "success" --no-close --no-buttons --infobox "Module created as $mod" 0 0 2000 &
	else
	    Xdialog --title "error" --msgbox "$mod creation failed!" 0 0 &
	fi
    else
	mkdir /tmp/rpm2xzm$$ && cp $y /tmp/rpm2xzm$$ && cd /tmp/rpm2xzm$$ && rpm2txz $pkg.rpm && txz2xzm $pkg.txz && mv $pkg.xzm $mod && echo -e "${c}Module created as $mod"$e || echo -e ''${r}$mod' creation failed!'$e
    fi
    rm -rf /tmp/rpm2xzm$$
done
