#!/bin/bash

# script by Ahau <ahau@porteus.org>
# script to change the volume in Porteus-XFCE
# channel is tied to the selected channel in volumeicon, so this requires retrovol (unless you only want to change Master Volume)
# adjusted by ncmprhnsbl @forum.porteus.org to use pamixer and (external) pygobject3 script: levelbar.py for gui part.
# next step is making this one pygobject script..

#some user editable variables:

#change to 0 if you don't want pygobject3 gui box
show_gui=1

# This will search the retrovol configs for the specified volume channel
# this file will not exist unless the user reconfigures retrovol, so it defaults to Master Playback Volume
# if ~/retrovolrc is not found.

virc=~/.config/volumeicon/volumeicon

if [ -e $virc ]; then
  step=`grep stepsize $virc |cut -d '=' -f2`
  vol_channel=`grep ^channel= $virc | cut -d '=' -f2`
fi

[ ! $step ] && step=5
[ ! $vol_channel ] && vol_channel='Master'
# afaics pulseaudio defaults to 'Master'

export vol_channel
export step

if [ "$1" = "up" ]; then
  #~ amixer set $vol_channel $step%+
  pamixer -i $step
fi

if [ "$1" = "down" ]; then
  #~ amixer set $vol_channel $step%-
  pamixer -d $step
fi

if [ "$1" = "toggle" ]; then
  #~ amixer set $vol_channel toggle
  pamixer -t
fi

# the rest will only be executed if the user wants to show the pygobject3 volume box(levelbar.py)
if [ "$show_gui" = "1" ]; then

  #~ vol_level=`amixer get $vol_channel|tail -n1| sed -r 's/.*\[(.*)%\].*/\1/'`
  vol_level=`pamixer --get-volume`
  echo $vol_level > /tmp/.pxf-volume

  unset sound_off
  #~ sound_off=`amixer get $vol_channel|tail -n1| grep '\[off\]'`
  sound_off=`pamixer --get-mute | grep "true"`
  # give info to levelbar.py
  if [ "$sound_off" ]; then
    echo "1" > /tmp/.pxf-status
  else
    echo "2" > /tmp/.pxf-status
  fi

  find_level (){
    #~ vol_level=`amixer get $vol_channel|tail -n1| sed -r 's/.*\[(.*)%\].*/\1/'`
    vol_level=`pamixer --get-volume`
    export vol_level
  }

  show_volume (){

  p=0
  python /opt/porteus-scripts/extra/levelbar.py &

  while [ "$p" -lt "12" ]; do
    #~ vol_status=`amixer get $vol_channel|tail -n1`
    vol_status=`pamixer --get-volume`
    find_level
    if [ "$vol_level" = 100 ]; then
      vol_level=99.5
    fi
    if [ "$vol_status" != "$vol_check" ]; then
      p=0
    fi
    echo $vol_level > /tmp/.pxf-volume
    vol_check=$vol_status
    sleep .125
    p=$(( p + 1 ));
    done
  echo 100 > /tmp/.pxf-volume
  }


  if [ "$1" = "toggle" ]; then
    old_pid=`ps aux |grep levelbar.py |grep -v grep|cut -d ' ' -f6,7|sed 's/ //g'`
    [ "$old_pid" ] && kill $old_pid
    show_volume
  fi

  if [ "$1" = "up" ]; then
    #if [ ! `ps aux | grep -v grep |grep levelbar.py` ]; then
      show_volume
    #fi
  fi

  if [ "$1" = "down" ]; then
    #if [ ! `ps aux | grep -v grep |grep levelbar.py` ]; then
      show_volume
    #fi
  fi

fi
