#!/bin/bash
# Service menu script to extract module/s to folder
# Author: Brokenman <brokenman@porteus.org>

. /usr/lib/librokenman

selection=$*
script="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"

# Root check
if [ "`whoami`" != "root" ]; then
  /opt/porteus-scripts/xorg/psu "$script $selection" &
  exit
fi

# Put up a dialog
export STATE=MANUAL
echo "Extracting $module ..." > /tmp/.message
manual_progress "Processing ..."

# Extract the modules
for module in $selection; do
  path=${module%/*}
  name=${module##*/}
  dir=${name%.*}
  echo $name >> /tmp/.extracted
  [ ! -d $path/$dir ] && mkdir $path/$dir
  echo "$name" > /tmp/.message
  xzm2dir $module $path/$dir
done

kill_manual_progress
export ext=`cat /tmp/.extracted`

# Give notification
echo '
'`start_window "Confirmation" gtk-yes 400 0`'
	<hbox>
		'`pixmapstock gtk-yes`'
		'`txtcolor 330 darkred x-large normal "Extraction was completed"`'
	</hbox>
		'`hsep`'
		'`blankline`'
		<timer milliseconds="true" visible="false">
             <action>sleep 2</action>
             <action type="exit">timedout</action>
           </timer>
'`end_window`'
'|gtkdialog -s

rm /tmp/.message /tmp/.extracted 2>/dev/null
exit

