#!/bin/bash
# Service menu script to convert txz/tgz packages to xzm modules
# Author: Brokenman <brokenman@porteus.org>

. /usr/lib/librokenman

COMP="-x"
COMP_ZSTD="-z"

while getopts "xz" opt; do
case "$opt" in

    x)
        shift "$(($OPTIND -1))"
        ;;

    z)
        COMP="$COMP_ZSTD"
        shift "$(($OPTIND -1))"
        ;;

esac
done

selection=$*
echo $selection >> /tmp/dbg

# Root check
if [ "`whoami`" != "root" ]; then
  /opt/porteus-scripts/xorg/psu $0 $COMP $selection &
  exit
fi

# Convert the packages
for package in $selection; do
  path=${package%/*}
  name=${package##*/}
  dir=${name%.*}
  #echo "$name" >> /tmp/.extracted
  #echo "$name" > /tmp/.message
  # start progress
  /usr/share/porteus/gtkprogress.py -w "Package Conversion" -m "Converting ${name}..." -t "Processing..." &
  #sleep 2
  mkdir /tmp/txz2xzm$$
  cp ${path}/${name} /tmp/txz2xzm$$
  cd /tmp/txz2xzm$$
  txz2xzm ${COMP} ${dir}.t?z
  mv $dir.xzm ${path}/
  rm -r /tmp/txz2xzm$$
  # kill progress
  prog=`ps ax|grep gtkprogress.py |awk '{print$1}'|head -n1`
  kill ${prog}

done




# Give notification
/usr/share/porteus/gtkdialog.py -p "Conversion complete!" -t 2000 &

#rm /tmp/.message /tmp/.extracted 2>/dev/null
exit

