#!/bin/bash
# Service menu script to convert txz/tgz packages to xzm modules
# Author: Brokenman <brokenman@porteus.org>

. /usr/lib/librokenman

COMP="-x"
COMP_ZSTD="-z"

while getopts "xz" opt; do
case "$opt" in

    x)
        shift "$(($OPTIND -1))"
        ;;

    z)
        COMP="$COMP_ZSTD"
        shift "$(($OPTIND -1))"
        ;;

esac
done

selection=$*
echo $selection >> /tmp/dbg

# Root check
if [ "`whoami`" != "root" ]; then
  /opt/porteus-scripts/xorg/psu $0 $COMP $selection &
  exit
fi

# Put up a dialog
export STATE=MANUAL
echo "Converting $package ..." > /tmp/.message
manual_progress "Processing ..."

# Convert the packages
for package in $selection; do
  path=${package%/*}
  name=${package##*/}
  dir=${name%.*}
  echo "$name" >> /tmp/.extracted
  echo "$name" > /tmp/.message
  mkdir /tmp/txz2xzm$$
  cp $path/$name /tmp/txz2xzm$$
  cd /tmp/txz2xzm$$
  txz2xzm $COMP $dir.t?z
  mv $dir.xzm $path/
  rm -r /tmp/txz2xzm$$
done

kill_manual_progress

# Give notification
/usr/share/porteus/gtkdialog.py -p "Conversion complete!" -t 2000

rm /tmp/.message /tmp/.extracted 2>/dev/null
exit

