#!/bin/bash
# Service menu script to extract module to folder
# Author: Brokenman <brokenman@porteus.org>

. /usr/lib/librokenman

if [ `grep "/" <<<$PWD` ]; then
path=${1%/*}
dir=${1##*/}
module=${dir}.xzm
  else
dir=${1}
path=`pwd`
module=${dir}.xzm
fi
script="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"

# Root check
#if [ "`whoami`" != "root" ]; then
#  /opt/porteus-scripts/xorg/psu "$script $1" &
#  unset dir module path
#  exit
#fi

if [ ! -w $path ]; then
	gtk_message "Sorry, $path is not writable!" 500 gtk-dialog-warning
	exit
fi

# Check for module
if [ -f "$path/$module" ]; then
  gtk_message "Sorry, $module already exists!" 500 gtk-dialog-warning
  exit
fi

export STATE=BUILDMODULE
echo "Creating $module ..." > /tmp/.message
manual_progress "Processing"
sleep 2
mksquashfs "$path/$dir" "$path/$module" >/tmp/.message -b 256K -Xbcj x86 -noappend || err=0
kill_manual_progress

if [ $err ]; then
	gtk_message "Sorry, could not create $mod!" 500 gtk-dialog-warning
	exit
fi

# Give notification
echo '
'`start_window "Confirmation" gtk-yes 400 0`'
	<hbox>
		'`pixmapstock gtk-yes`'
		'`txtcolor 330 darkred x-large normal "$module was created."`'
	</hbox>
		'`hsep`'
		'`blankline`'
		<timer milliseconds="true" visible="false">
             <action>sleep 2</action>
             <action type="exit">timedout</action>
           </timer>
'`end_window`'
'|gtkdialog -s

rm /tmp/.messsage 2>/dev/null
exit
