#!/bin/bash
# Service menu script to extract module/s to folder
# Author: Brokenman <brokenman@porteus.org>

. /usr/lib/librokenman
IFS=$'\n'
selection=$*
script="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
# Root check
#if [ "`whoami`" != "root" ]; then
#  /opt/porteus-scripts/xorg/psu "$script $selection" &
#  exit
#fi

error(){
/usr/share/porteuse/gtkdialog.py -p "An error ocurred" -d err
#echo '
#'`start_window "Error" gtk-yes 400 0`'
#	<hbox>
#		'`pixmapstock gtk-no`'
#		'`txtcolor 330 darkred x-large normal "An error ocurred"`'
#	</hbox>
#		'`hsep`'
#		'`blankline`'
#		<timer milliseconds="true" visible="false">
#             <action>sleep 2</action>
#             <action type="exit">timedout</action>
#           </timer>
#'`end_window`'
#'|gtkdialog -s
exit
}

p=${1%/*}
if [ ! -w $p ]; then
	error
	exit
fi

# Put up a dialog
export STATE=MANUAL
echo "Extracting $module ..." > /tmp/.message
manual_progress "Processing ..."

# Extract the modules
for module in $selection; do
  path=${module%/*}
  name=${module##*/}
  dir=${name%.*}
  echo $name >> /tmp/.extracted
  [ ! -d "$path/$dir" ] && mkdir "$path/$dir"
  unsquashfs -f -dest "$path/$dir" $module
  echo "$name" > /tmp/.message
done

kill_manual_progress
export ext=`cat /tmp/.extracted`

# Give notification
/usr/share/porteuse/gtkdialog.py -p "Extraction was completed" -t 2000
#echo '
#'`start_window "Confirmation" gtk-yes 400 0`'
#	<hbox>
#		'`pixmapstock gtk-yes`'
#		'`txtcolor 330 darkred x-large normal "Extraction was completed"`'
#	</hbox>
#		'`hsep`'
#		'`blankline`'
#		<timer milliseconds="true" visible="false">
#             <action>sleep 2</action>
#             <action type="exit">timedout</action>
#           </timer>
#'`end_window`'
#'|gtkdialog -s

rm /tmp/.message /tmp/.extracted 2>/dev/null
exit

