#!/bin/bash
# Service menu script to mount module on loop
# Author: Brokenman <brokenman@porteus.org>

. /usr/lib/librokenman

file=$1
name=${file##*/}
script="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"

# Root check
if [ "`whoami`" != "root" ]; then
  /opt/porteus-scripts/xorg/psu $script $file &
  exit
fi

message_good(){
/usr/share/porteus/gtkdialog.py -p "$name was mounted" -s "$name was successfully mounted at /mnt/loop" -t 2000	
#~ echo '
#~ '`start_window "Mounted" gtk-yes 400 0`'
	#~ <hbox>
		#~ '`pixmapstock gtk-help`'
		#~ '`txtcolor 330 darkred x-large normal "$name was mounted"`'
	#~ </hbox>
		#~ '`hsep`'
		#~ '`txtmarkup 370 "$name was successfully mounted at /mnt/loop"`'
	#~ <timer milliseconds="true" visible="false">
             #~ <action>sleep 2</action>
             #~ <action type="exit">timedout</action>
      #~ </timer>
#~ '`end_window`'
#~ '|gtkdialog -s > /tmp/.message
}

message_bad(){
/usr/share/porteus/gtkdialog.py -p "$name was NOT mounted" -s "There was an error mounting $name at /mnt/loop" -d err	
#~ echo '
#~ '`start_window "Not mounted" gtk-yes 400 0`'
	#~ <hbox>
		#~ '`pixmapstock gtk-error`'
		#~ '`txtcolor 330 darkred x-large normal "$name was NOT mounted"`'
	#~ </hbox>
		#~ '`hsep`'
		#~ '`txtmarkup 370 "There was an error mounting $name at /mnt/loop"`'
     #~ <timer milliseconds="true" visible="false">
             #~ <action>sleep 2</action>
             #~ <action type="exit">timedout</action>
     #~ </timer>
#~ '`end_window`'
#~ '|gtkdialog -s > /tmp/.message
}

mloop $file && message_good || message_bad

rm /tmp/.message
