#!/bin/bash
# Service menu script to unistall slackware packages
# Author: Brokenman <brokenman@porteus.org>

. /usr/lib/librokenman

selection=$*

# Root check
if [ "`whoami`" != "root" ]; then
  /opt/porteus-scripts/xorg/psu $0 $selection &
  exit
fi

# Put up a dialog
export STATE=MANUAL
echo "Removing $package ..." > /tmp/.message
manual_progress "Processing ..."

# Remove the packages
for package in $selection; do
  path=${package%/*}
  name=${package##*/}
  dir=${name%.*}
  echo "$name" >> /tmp/.extracted
  echo "$name" > /tmp/.message
  removepkg $package
done

kill_manual_progress

# Give notification
/usr/share/porteus/gtkdialog.py -p "Package removal complete" -t 2000
#~ echo '
#~ '`start_window "Confirmation" gtk-yes 400 0`'
	#~ <hbox>
		#~ '`pixmapstock gtk-yes`'
		#~ '`txtcolor 330 darkred x-large normal "Package removal complete"`'
	#~ </hbox>
		#~ '`hsep`'
		#~ '`blankline`'
		#~ <timer milliseconds="true" visible="false">
             #~ <action>sleep 2</action>
             #~ <action type="exit">timedout</action>
           #~ </timer>
#~ '`end_window`'
#~ '|gtkdialog -s

rm /tmp/.message /tmp/.extracted 2>/dev/null
exit

