#!/bin/sh

# [Pluma Tool]
# Name=Build
# Name[am]=መገንቢያ
# Name[bg]=Компилиране
# Name[ca]=Construeix
# Name[ca@valencia]=Munta
# Name[cs]=Sestavit
# Name[da]=Byg
# Name[de]=Alles kompilieren
# Name[el]=Χτίσιμο
# Name[en_GB]=Build
# Name[es]=Construir
# Name[fr]=Construire
# Name[hu]=Összeállítás
# Name[id]=Bangun
# Name[it]=Crea
# Name[ja]=ビルド
# Name[kk]=Жинау
# Name[ko]=빌드하기
# Name[lt]=Sukurti
# Name[ms]=Binaan
# Name[nb]=Byggversjon
# Name[nl]=Bouwen
# Name[pl]=Zbudowanie
# Name[pt]=Compilação
# Name[pt_BR]=Compilar
# Name[ro]=Construire
# Name[ru]=Сборка
# Name[sk]=Zostavenie
# Name[sr]=Изгради
# Name[sv]=Bygg
# Name[tr]=Derle
# Name[uk]=Збірка
# Name[zh_CN]=构建
# Name[zh_TW]=建構
# Comment=Run "make" in the document directory
# Comment[am]=ማስኬጃ "መስሪያ" በ ሰነድ ዳይሬክቶሪ ውስጥ
# Comment[bg]=Стартиране на „make“ в папката на документа
# Comment[ca]=Executa «make» al directori del document
# Comment[ca@valencia]=Executa «make» al directori del document
# Comment[cs]=Spustit „make” v adresáři dokumentu
# Comment[da]=Start »make« i dokumentmappen
# Comment[de]=»make« im Dokumentenordner ausführen
# Comment[el]=Εκτέλεση "make" στον κατάλογο εγγράφου
# Comment[en_GB]=Run "make" in the document directory
# Comment[es]=Ejecutar "make" en el directorio del documento
# Comment[fr]=Exécuter « make » dans le répertoire du document
# Comment[hu]=A „make” futtatása a dokumentum könyvtárában
# Comment[id]=Jalankan "make" di dalam direktori dokumen
# Comment[it]=Esegue «make» nella cartella del documento
# Comment[ja]=文書のあるディレクトリで "make" を実行
# Comment[kk]=Құжат бумасында "make" жөнелту
# Comment[ko]=문서 디렉터리에서 "make"를 실행합니다
# Comment[lt]=Vykdyti „make“ dokumento kataloge
# Comment[ms]=Jalankan "make" dalam direktori dokumen
# Comment[nb]=Kjør "make" i dokumentmappa
# Comment[nl]=‘maken’ uitvoeren in de documentmap
# Comment[pl]=Wykonuje "make" w katalogu dokumentu
# Comment[pt]=Executar "make" no directório do documento
# Comment[pt_BR]=Executar "make" no diretório do documento
# Comment[ro]=Execută „make” în dosarul documentului
# Comment[ru]=Выполнить «make» в каталоге с документом
# Comment[sk]=Spustiť „make“ v priečinku dokumentu
# Comment[sl]=Zaženi "make" v imeniku dokumenta
# Comment[sr]=Покрените „make“ у директоријуму документа
# Comment[sv]=Kör "make" i dokumentkatalogen
# Comment[tr]=Belge dizininde "make" çalıştır
# Comment[uk]=Виконати «make» у каталозі з документом
# Comment[zh_CN]=在文档所在的目录运行“make”
# Comment[zh_TW]=在文件資料夾中執行「make」指令
# Input=nothing
# Output=output-panel
# Shortcut=<Control>F8
# Applicability=local
# Save-files=nothing
# Languages=

EHOME=`echo $HOME | sed "s/#/\#/"`
DIR=$PLUMA_CURRENT_DOCUMENT_DIR
while test "$DIR" != "/"; do
    for m in GNUmakefile makefile Makefile; do
        if [ -f "${DIR}/${m}" ]; then
            echo "Using ${m} from ${DIR}" | sed "s#$EHOME#~#" > /dev/stderr
            make -C "${DIR}"
            exit
        fi
    done
    DIR=`dirname "${DIR}"`
done
echo "No Makefile found!" > /dev/stderr
