#!/bin/sh
# Update XFCE menu:

RUNNINGPROCESSES=`ps -ef`
# Update Whiskermenu if it is being used
if [[ $RUNNINGPROCESSES == *"whiskermenu"* ]]; then
	kill -10 `ps -ef | grep whiskermenu | grep -v grep | awk '{print $2}'`
fi

update-desktop-database
