#!/bin/bash
# Script to unmount module mounted at /mnt/loop
# This script is called by thunar service menu
# Author: Brokenman <brokenman@porteus.org>
# Modified for lxde by Ahau <ahau@porteus.org>

. /usr/lib/librokenman

selection=$*

# Root check
if [ "`whoami`" != "root" ]; then
  /opt/porteus-scripts/xorg/psu "$0 $selection" &
  exit
fi

fullpath=${1}
path=${fullpath%/*}
mod=`echo $fullpath | rev | cut -d/ -f1 | rev`

if [ -d /mnt/loop ]; then
	chk=`cut -d" " -f2 /proc/mounts | grep -w /mnt/loop`
		if [ "$chk" == "" ]; then
			gtk_message "$mod is not mounted at /mnt/loop" 500 gtk-dialog-warning
			exit
				else
			umount /mnt/loop
			gtk_message "/mnt/loop was unmounted" 500 gtk-yes
			exit
		fi
		else
	gtk_message "$mod is not mounted at /mnt/loop" 500 gtk-dialog-warning
fi
exit
