#!/bin/bash

# CLI Google Translator
# scriptname en pt "this is a test"
# Author: brokenman
# 22nd Jan 2014

# Color definitions
txtund=$(tput sgr 0 1)          # Underline
txtbld=$(tput bold)             # Bold
rst=$(tput sgr0)             # Reset

translate(){
wget -U "Mozilla/5.0" -qO - "http://translate.google.com/translate_a/t?client=t&text=$CONV&sl=$L1&tl=$L2" | sed 's/\[\[\[\"//' | cut -d \" -f 1
}

usage(){
echo
echo "Usage: `basename $0` lang1 lang2 <string>"
echo "Example:" $txtbld "`basename $0` en pt \"this is a test\"" $rst
echo
exit
}

[ -z $1 ] && usage
[[ `grep -o "\-h|\-help|\--help|help|\?" <<<$1` ]] && usage
[ $# -lt 3 ] && usage

L1=$1
shift
L2=$1
shift

REST=$@
for a in $REST; do
    b="$a+"
    CONV="${CONV}$b"
done
CONV=`echo $CONV|sed 's/\(.*\)./\1/'`
translate

