'\" t
.\"     Title: pm-is-supported
.\"    Author: Tim Dijkstra <tim@famdijkstra.org>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: Apr 18, 2007
.\"    Manual: pm-utils User Manual
.\"    Source: pm-is-supported
.\"  Language: English
.\"
.TH "PM\-IS\-SUPPORTED" "1" "Apr 18, 2007" "pm-is-supported" "pm-utils User Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pm-is-supported \- Test whether suspend or hibernate is supported\&.
.SH "SYNOPSIS"
.HP \w'\fBpm\-is\-supported\fR\ 'u
\fBpm\-is\-supported\fR [{\fB\-\-suspend\fR\ |\ \fB\-\-hibernate\fR\ |\ \fB\-\-suspend\-hybrid\fR}]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBpm\-is\-supported\fR
command\&.
.PP
The intended purpose of
\fBpm\-is\-supported\fR
is to find out which power management modes are supported by the system\&. hald(8) will call it to do just that\&. (Note that UPower does not use this\&.)
.SH "OPTIONS"
.PP
\fB\-\-suspend\fR
.RS 4
Test whether suspend is supported\&. Suspend is a state where most devices are shutdown, except for RAM\&. This state still draws power\&.
.RE
.PP
\fB\-\-hibernate\fR
.RS 4
Test whether hibernate is supported\&. During hibernate the state of the system is saved to disk, the system is fully powered off\&.
.RE
.PP
\fB\-\-suspend\-hybrid\fR
.RS 4
Test whether hybrid\-suspend is supported\&. Hybrid\-suspend is the process where first the state of the system is saved to disk \-\- just like with hibernate \-\- but instead of poweroff, the system goes in suspend state, which means it can wakeup quicker than for normal hibernation\&. The advantage over suspend is that you can resume even if you run out of power\&. s2both is a hybrid\-suspend implementation\&.
.RE
.SH "RETURN VALUE"
.PP
The result of the test for a certain powermanagement state is defined by the following exit codes\&.
.\" line length increase to cope w/ tbl weirdness
.ll +(\n(LLu * 62u / 100u)
.TS
ll.
\fICode\fR	\fIDiagnostic\fR
T{
\fB0\fR
T}	T{
State available\&.
T}
T{
\fB1\fR
T}	T{
State NOT available\&.
T}
.TE
.\" line length decrease back to previous value
.ll -(\n(LLu * 62u / 100u)
.sp
.SH "SEE ALSO"
.PP

\fBhald\fR(8),
\fBpm-suspend\fR(8),
\fBs2both\fR(8),
\fBUPower\fR(7)
.SH "AUTHOR"
.PP
\fBTim Dijkstra\fR <\&tim@famdijkstra\&.org\&>
.RS 4
Manpage author\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2007 Tim Dijkstra
.br
.PP
This manual page was originally written for the
Debian(TM)
system, and has been adopted by the pm\-utils project\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 or (at your option) any later version published by the Free Software Foundation\&.
.sp
