#!/bin/bash
#pfilesearch
#version=1.X
#language=english

# |==================================|
# | <b>text</b>            Bold text |
# |==================================|

export LOC_SEARCH="Search"
export LOC_OK="Ok"
export LOC_CANCEL="Cancel"
export LOC_INFO="Info"
export LOC_ERROR="Error"
export LOC_YES="Yes"
export LOC_NO="No"
LOC_QUIT="Quit"
LOC_IN="in"
LOC_FOR="for" #(search for)
LOC_FROM="from"
LOC_TO="to"
LOC_OPTIONS="Options"
LOC_SEARCHTEXT="Search text"
LOC_EXCLUDE="Exclude"
LOC_FILE="File"
LOC_SYMLINK="Symlink"
LOC_DIRECTORY="Directory"
LOC_ALL="All"
LOC_DOCUMENTS="Documents"
LOC_PICTURES="Pictures"
LOC_SOUNDFILES="Music"
LOC_VIDEOS="Videos"
LOC_MAILS="E-Mails"
LOC_COMPRESSED="Compressed files"
LOC_CODEFILES="Code files"

#gui
LOC200="Filename"
LOC505="Text in file (slow)"
LOC506="Search also subdirectories"
LOC507="Search only current filesystem"
LOC508="Match only exact filename"
LOC509="Case sensitive"
LOC510="Follow symlinks"
LOC512="Match only"
LOC513="Match date"
LOC515="Match size"
LOC516="Greater than"
LOC517="Less than"
LOC518="Match user"
LOC519="Name or ID"
LOC520="Match mode"
LOC521="Read"
LOC522="Write"
LOC523="Exec"
LOC524="User"
LOC525="Group"
LOC526="Other"
LOC102="Preferences"

#configure
LOC309="MIME"
LOC310="Searchpath"

#info
export LOC311="If wanted, there can be several searchpaths.
Separate paths with <b>[OR]</b>: '/mnt/ [OR] /root/'.
'./' is used to specify current path."
export LOC312="- Searching for 'text in file' is MUCH slower than 'filename'.
- Regular expressions works only when searching for filenames (not Text in file).
- If having problems with local chars, use ? instead of char."
export LOC313="To define an exact search, you can use the terms:
<b>[OR]</b> Filename/content must contain either 'this [OR] that'. This will give more results.
<b>[AND]</b> Filename/content must contain both 'this [AND] that'. This will give less results.
<b>*</b> Means anything. 'pup*back' finds both 'PuppyBackup' and 'Puppies are back'.
<b>?</b> Means any char. 'pup??back' finds only 'PuppyBackup'. '??' represent only two chars."
export LOC314="format: MM/DD/YYYY. 
<b>atime</b> - day file was accessed.
<b>ctime</b> - day file changed 
(The actual content of file has changed).
<b>mtime</b> - day inode was modified  (The attributes or status of file has changed - date, permissions...)."
export LOC315="<b>1k</b> = 1 kilobyte (small k).
<b>1M</b> = 1 megabyte (big M).
<b>1G</b> = 1 gigabyte (big G)."
export LOC316="Define a directory, and it will NOT be in the searchpath. Setting works recursively."

#Misc
LOC500="Searching"
LOC601="all files"
LOC602="Note! The first search will be much slower than the next"

#Errors
export LOC700="Date can't be earlier than 1/1 1970."
export LOC701="No files found!"
export LOC702="is not installed"
export LOC703="Can't find"
