#!/bin/bash
# Convert Slackware's package(s) into .xzm module
#
# Author: Tomas M. <http://www.linux-live.org>
# Modifications for Porteus by fanthom


# Exit if nothing is provided as an argument:
if [ "$1" = "" ]; then
    echo
    echo "Convert Slackware's TXZ package into .xzm compressed module"
    echo "usage:"
    echo
    echo "$0 package.txz"
    echo "$0 package1.txz package2.txz package3.txz"
    echo "$0 /folder/with_packages/*"
    exit 1
fi

# Work only on txz/tgz packages:
for x in $*; do
    ext=`echo $x | rev | cut -d. -f1 | rev`
    if [ "$ext" = txz -o "$ext" = tgz ]; then
	mod=`readlink -f $x`
	MOD=`echo $MOD $mod`
    fi
done

# Switch to root:
if [ "$DISPLAY" ]; then
    if [ `whoami` != "root" ]; then
	/opt/porteus-scripts/xorg/psu "/opt/porteus-scripts/txz2xzm $MOD"
	exit
    fi
else
    if [ `whoami` != "root" ]; then
	echo "Please enter root's password below"
        su - -c "/opt/porteus-scripts/txz2xzm $MOD"
        exit
    fi
fi

# Create module:
for y in $MOD; do
    TMPDIR=/tmp/txz2xzm$$
    XZM="`echo $y | rev | cut -d. -f2- | rev`.xzm"

    installpkg -root $TMPDIR $y
    if [ $? != 0 ]; then echo "error installing $y package"; exit; fi

    # optimalization procedures, this doesn't hurt
    find $TMPDIR/usr{/local/,/share/,/}{man,info} -type l -name "*.gz" 2>/dev/null | xargs -r gunzip -f
    find $TMPDIR/usr{/local/,/share/,/}{man,info} -type f -name "*.gz" 2>/dev/null | xargs -r gunzip
    cp -a $TMPDIR/usr/share/man $TMPDIR/usr 2>/dev/null; rm -rf $TMPDIR/usr/share/man
    rm -f $TMPDIR/{usr,usr/local,var}/man/cat*/*

    echo -e "Creating $XZM\n"
    dir2xzm $TMPDIR $XZM >/dev/null
    if [ $? != 0 ]; then echo "error building compressed image"; exit; fi

    rm -Rf $TMPDIR
done
