'\" t
.\"     Title: udisks-tcp-bridge
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: December 2009
.\"    Manual: udisks-tcp-bridge
.\"    Source: udisks
.\"  Language: English
.\"
.TH "UDISKS\-TCP\-BRIDGE" "1" "December 2009" "udisks" "udisks-tcp-bridge"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
udisks-tcp-bridge \- udisks TCP/IP bridge
.SH "SYNOPSIS"
.HP \w'\fBudisks\-tcp\-bridge\ \fR\ 'u
\fBudisks\-tcp\-bridge \fR [\fB\-\-port\fR\ \fIport\fR] [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
This program is used by remote clients to connect to the
\fIorg\&.freedesktop\&.UDisks\fR
D\-Bus service on the system bus\&.
.PP
Users or administrators never needs to start this program as it started automatically by a remote client connecting via
\fBssh\fR(1)\&. See the
\fBudisks\fR(7)
manual page for information about the higher level connection protocol used\&.
.SH "AUTHOR"
.PP
Written by David Zeuthen
<david@fubar\&.dk>
with a lot of help from many others\&.
.SH "BUGS"
.PP
Please send bug reports to either the distribution bug tracker or the upstream bug tracker at
\m[blue]\fB\%http://bugs.freedesktop.org/enter_bug.cgi?product=udisks\fR\m[]\&.
.SH "SEE ALSO"
.PP
\fBudisks-daemon\fR(8),
\fBudisks\fR(7),
\fBudisks\fR(1),
\fBssh\fR(1)
