#!/bin/bash


function browser_open(){
local BROWSERLIST="firefox opera google-chrome-stable konqueror chromium"
local URL=$1

local USERX=`< $TMPDIR/user`

[[ -x $BROWSER ]] && { su - $USERX -c "$BROWSER $URL"; exit; }

for a in gvfs-open gnome-open xdg-open; do
	hash $a 2>/dev/null && { local OPENER=$a; break; } || unset OPENER
done

if [ -z $OPENER ]; then
	for a in $BROWSERLIST; do
		hash $a 2>/dev/null && { local OPENER=$a; break; }
	done
fi

[ -z $OPENER ] && { echo "`gettext "No internet browser found."`"; cleanup; }

su - $USER -c "$OPENER http://google.com"
}; export -f browser_open

set_storage(){
local PTH=$1
[ ! -d $PTH ] && { echo "$1 does not exist."; cleanup; }
[ ! -w $PTH ] && { echo "$1 is not writable."; cleanup; }
local CVAL=`grep "STORAGE=" $CONF`
local NVAL="STORAGE=$PTH"
sed -i "s@$CVAL@$NVAL@g" $CONF || { echo "Failed!"; cleanup; }
echo
echo "Storage updated: $PTH"
cleanup
}
