#!/bin/bash
## This script will create a gtkdialog window
## that will act as a front end to the slackware
## script, 'timeconfig', to allow users to set
## their local timezone (if needed) and save
## those settings to a porteus xzm module.

## script by ahau, based on gtkdialog examples 
## by brokenman and timeconfig, by Patrick Volkerding

. /usr/lib/librokenman

## Switch to root
if [ `whoami` != "root" ]; then
    gtk_message "Only root can run this application!" 400 gtk-dialog-error
    exit
fi

exec 2>/dev/null

## Variables
export TZSET="/tmp/tzset_$$"
export PIXMAPS=/usr/share/pixmaps/porteus
export PAGELOCK=$TZSET/.pagelock

##variables from timeconfig
export HWCLOCK_CONF=/etc/hardwareclock

mkdir -p $TZSET

## Create the page lock file to hold the notebook pages. (0 is page 1)
echo 0 > $PAGELOCK

## Is user using changes= ?
grep "changes=" /proc/cmdline && export using_changes=1 || unset using_changes

## Can we see modules folder?
modf=`ls -l /mnt/live/porteus/modules|awk '{print$NF}'`
[ -w $modf ] && export mods=${modf} || unset mods modf

## check existing status of /etc/hardwareclock (UTC or localtime) and /etc/localtime
export hwc_orig_state=`cat /etc/hardwareclock | grep -v '^#' |grep -v '^$'`
export lcf_orig_state=`readlink -f /etc/localtime-copied-from`
if [ -e /etc/localtime ]; then
  cp -a /etc/localtime $TZSET/lt_backup
fi

## export existing status as variables, to set defaults in the gtk window
if [ "$hwc_orig_state" = "localtime" ]; then
  export localtf=true
else
  export localtf=false
fi

if [ "$hwc_orig_state" = "UTC" ]; then
  export utctf=true
else
  export utctf=false
fi

if [ "$utctf" = "true" ]; then
  export combo_sens=enabled
else
  export combo_sens=disabled
fi

export orig_tz="`readlink -f /etc/localtime-copied-from|sed 's@/usr/share/zoneinfo/@@g'`"
if [ "$orig_tz" = "Factory" ]; then
  export orig_tz='(none specified)'
fi

#place existing configs in dump to make sure they don't disappear on us now that we've made them defaults
echo "system clock is $hwc_orig_state" >> $TZSET/dump
echo "selected timezone is $orig_tz" >> $TZSET/dump

#get currently displayed timezone
find_new_timezone()
{
unset localselect
localselect=`cat $TZSET/dump|grep "system clock is"|tail -n 1 |grep localtime`
if [ "$localselect" ]; then
  echo "`date --utc +%H:%M`   (`date --utc +"%I:%M %p"`)      " > $TZSET/timenow
else
  unset utcselect
  utcselect=`cat $TZSET/dump|grep "system clock is"|tail -n 1 |grep -i utc`
  if [ "$utcselect" ]; then 
    tzselect=`cat $TZSET/dump|grep "selected timezone is"|grep -v none|tail -n 1 |sed 's/selected timezone is //g'`
    echo "`TZ="$tzselect" date +%H:%M`   (`TZ="$tzselect" date +"%I:%M %p"`)      " > $TZSET/timenow
  fi
fi
}; export -f find_new_timezone

find_new_timezone

## generate timezone list
cat /usr/sbin/timeconfig |sed '/^US\/Alaska/,/^right\/Zulu/!d' > /tmp/.tzset_list
sed -i '1 i \(none specified)' /tmp/.tzset_list

## writeconf function copied from slackware 'timeconfig'
# writeconf( $CLOCK_SET_TO )
#
# Writes out $HWCLOCK_CONF that tells rc.S how the hardware clock
# value is stored.
writeconf()
{
   echo "# /etc/hardwareclock" > $HWCLOCK_CONF
   echo "#" >> $HWCLOCK_CONF
   echo "# Tells how the hardware clock time is stored." >> $HWCLOCK_CONF
   echo "# You should run timeconfig to edit this file." >> $HWCLOCK_CONF
   echo >> $HWCLOCK_CONF
   echo $1 >> $HWCLOCK_CONF
}; export -f writeconf

## setzone function, also copied from 'timeconfig'
# setzone( $TIMEZONE )
#
# This function accepts a time zone as the only parameter and sets it as
# the default system time zone.
setzone()
{
   TZ=$1

   cd /etc
   if [ -r /usr/share/zoneinfo/$TZ -o \
        -r /var/log/mount/usr/share/zoneinfo/$TZ -o \
        -L /usr/share/zoneinfo/$TZ -o \
        -L /var/log/mount/usr/share/zoneinfo/$TZ ]; then
      ln -sf /usr/share/zoneinfo/$TZ localtime-copied-from
      rm -f localtime
      cd ..
      chroot . cp etc/localtime-copied-from etc/localtime
   fi
}; export -f setzone


## setup info for date/time comboboxes

echo "01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" | tr " " "\n" >> /tmp/.tzset_date_date
echo "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec" | tr " " "\n" >> /tmp/.tzset_date_month
echo "2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023" | tr " " "\n" >> /tmp/.tzset_date_year

#get current date/time

export cur_date_date=`date +%d`  && echo new date_date is $cur_date_date >> $TZSET/dump
export cur_date_month=`date +%b` && echo new date_month is $cur_date_month >> $TZSET/dump
export cur_date_year=`date +%Y` && echo new date_year is $cur_date_year >> $TZSET/dump
export cur_date_hour=`date +%H` && echo new date_hour is $cur_date_hour >> $TZSET/dump
export cur_date_minute=`date +%M` && echo new date_minute is $cur_date_minute >> $TZSET/dump

apply_new_time()
{
  
  . /usr/lib/librokenman
  
  newdate=`cat $TZSET/dump |grep "new date_date"|tail -n 1 |sed 's/new date_date is //g'`
  newmonth=`cat $TZSET/dump |grep "new date_month"|tail -n 1 |sed 's/new date_month is //g'`
  newyear=`cat $TZSET/dump |grep "new date_year"|tail -n 1 |sed 's/new date_year is //g'`
  newhour=`cat $TZSET/dump |grep "new date_hour"|tail -n 1 |sed 's/new date_hour is //g'`
  newminute=`cat $TZSET/dump |grep "new date_minute"|tail -n 1 |sed 's/new date_minute is //g'`
  
  date -s "$newdate $newmonth $newyear $newhour:$newminute"
  
  if [ "$?" == "0" ]; then
   gtk_message "Your system time has been set.  You may need to log out of your Desktop Environment before the clock is updated to reflect the new time." 450 gtk-yes
  else
   gtk_message "Some error occurred, please check the syntax and try again, or report this issue on the Porteus forum." 500 gtk-yes
  fi

}; export -f apply_new_time


set_utc_tz()
{
	
  . /usr/lib/librokenman
	
utcselect=`cat $TZSET/dump|grep "system clock is"|tail -n 1 |grep -i utc`
if [ "$utcselect" ]; then 
  writeconf UTC
  tzselect=`cat $TZSET/dump|grep "selected timezone is"|grep -v none|tail -n 1 |sed 's/selected timezone is //g'`
  [ "$tzselect" ] && setzone $tzselect
fi

localselect=`cat $TZSET/dump|grep "system clock is"|tail -n 1 |grep localtime`
if [ "$localselect" ]; then
  rm /etc/localtime
  writeconf localtime
  (cd /etc && rm -f /etc/localtime-copied-from && ln -sf /usr/share/zoneinfo/Factory localtime-copied-from)
fi


#check if any changes were made to original settings:
unset did_modify
if [ `cat /etc/hardwareclock | grep -v '^#' |grep -v '^$'` != "$hwc_orig_state" ]; then
  did_modify=true
fi
if [ ! -e $TZSET/lt_backup ]; then
  if [ -e /etc/localtime]; then
    did_modify=true
  fi
elif [ "`md5sum $TZSET/lt_backup|cut -d ' ' -f1`" != "`md5sum /etc/localtime|cut -d ' ' -f1`" ]; then
    did_modify=true
fi

if [ `readlink -f /etc/localtime-copied-from` != "$lcf_orig_state" ]; then
  did_modify=true
fi

if [ ! "$did_modify" ]; then
   gtk_message "No changes were made to your existing configuration." 450 gtk-yes
else
   gtk_message "Your changes have been applied.  Please log out and then back in to update your panel clock (LXDE/Xfce users can just wait a moment for it to update)." 500 gtk-yes
fi

## prompt user to create a module
if [ "$using_changes" != "1" -a "$did_modify" ]; then

export ASK_ME='
'`start_window "Yes or no" cdr 450`'
  <frame>
    <hbox>
      '`pixmapstock gtk-dialog-question`'
      <text use-markup="true" width-request="375" selectable="true" can-focus="no">
      <label>"You do not appear to be saving your Porteus changes. You should create a module for your changes which will be loaded every time you boot.  Would you like to create the module now?"</label></text>
  </hbox>
  </frame>
  <hbox>
    '`butyes`'
    '`butno`'
  </hbox>
'`end_window`'
'
for a in `gtkdialog -p ASK_ME`; do
  if [ `egrep -o "abort|No|no" <<<$a` ]; then
    exit
  fi
  if [ `egrep -o "Yes|yes" <<<$a` ]; then
    answ=yes
      else
    unset answ
  fi
done

  if [ "$answ" == "yes" ]; then
    unset answ
    if [ "$mods" ]; then
      mkdir -p $TZSET/fakeroot/etc
	cp -a /etc/localtime $TZSET/fakeroot/etc/
	cp -a /etc/localtime-copied-from $TZSET/fakeroot/etc/
	cp -a /etc/hardwareclock $TZSET/fakeroot/etc/
	
      mksquashfs $TZSET/fakeroot/ $mods/timeconfig.xzm -b 256K -Xbcj x86 -noappend
      gtk_message "Your timeconfig.xzm module will now be activated when you boot Porteus." 450 gtk-yes
        else
      ## The modules folder is not available
      mksquashfs $TZSET/fakeroot/etc /tmp/timeconfig.xzm -keep-as-directory
      gtk_message "Your porteus/modules folder was not found or is unwritable. Please copy the file /tmp/timeconfig.xzm into the modules folder or base folder." 500 gtk-no
    fi
  fi
fi	
	
}; export -f set_utc_tz



export TIMECONFIG='
<window window_position="1" title="Date and Time Settings" icon-name="clock" allow-shrink="false" width-request="640" height-request="480">
<vbox margin="10">
  <hbox>
    '`pixmapfile 64 64 /usr/share/pixmaps/porteus/App-world-clock-icon.png`'
    '`txtcolor 400 darkred x-large normal "            Porteus Date and Time Settings"`'
  </hbox>
    '`hsep`'
    <notebook show-tabs="false" show-border="false" labels="Start|SetClock|Timezone" height-request="380">
    <vbox>
    <frame Set Clock or Select Timezone?>
      <hbox>
      <text xalign="0" wrap="true" width-request="590"><label>"
This application will allow you to change the date and time of your system clock.  You can also use it to select your local timezone if your system clock is set to UTC time.
"</label>        
      </text>
      </hbox>
      
      <hseparator></hseparator>
   <vbox>      
    <hbox>

      <text xalign="0" wrap="true" width-request="590"><label>"
If the date and/or time for your system is incorrect (for example, due to a failed battery), Please click the '"'Set Date/Time'"' button below."</label>        
      </text>
      </hbox>
      <hbox>

        <button tooltip-text="Date/Time">
		<label>Set Date/Time</label>
		<input file stock="gtk-apply"></input>
		<action>echo 1 > '$PAGELOCK'</action>
		<action>refresh:nbkMain</action>
		</button>
      
      </hbox>
          <hbox>

      <text xalign="0" wrap="true" width-request="590"><label>""</label>        
      </text>
      </hbox>
   </vbox>
      
      <hseparator></hseparator>
   <vbox>   
    <hbox>
      <text xalign="0" wrap="true" width-request="590"><label>"
If your hardware clock is set to UTC time and you would like to change your timezone so that the correct hour is displayed on your system clock, then click the '"'Select a Timezone'"' button below."</label>        
      </text>
    </hbox>
    <hbox>
        <button tooltip-text="Select a Timezone">
		<label>Set Timezone</label>
		<input file stock="gtk-apply"></input>
		<action>echo 2 > '$PAGELOCK'</action>
		<action>refresh:nbkMain</action>
		</button>
    
    </hbox>
   </vbox>
      
    </frame>
  <hbox>
  
    <button cancel>
    </button>
  </hbox>
</vbox>

<vbox>
    <frame Set Date/Time>
    <hbox>
<text use-markup="true" xalign="0" wrap="true" width-request="590"><label>"
Please enter the correct date and time below, and then click '"'Apply'"' to set the system clock.

Note: Use a 24-hour clock rather than AM/PM, for example: 12 Feb 2013 15:34
"</label></text>
    </hbox>
          <hseparator></hseparator>    
     <vbox>
              <text use-markup="true" selectable="true" can-focus="no" width-request="175">
    <label>""</label></text>
    </vbox>
     
     <hbox>

     
    <comboboxtext focus-on-click="false" width-request="50">
	<variable>DATE_DATE</variable>
	<input file>/tmp/.tzset_date_date</input>
	<default>'`echo $cur_date_date`'</default>
	<action signal="changed">echo new date_date is $DATE_DATE >> $TZSET/dump</action>
	<action signal="changed">enable:TAPPLY</action>
    </comboboxtext>
  
    <comboboxtext focus-on-click="false" width-request="55">
	<variable>DATE_MONTH</variable>
	<input file>/tmp/.tzset_date_month</input>
	<default>'`echo $cur_date_month`'</default>
	<action signal="changed">echo new date_month is $DATE_MONTH >> $TZSET/dump</action>
	<action signal="changed">enable:TAPPLY</action>
    </comboboxtext>   
    
    <comboboxtext focus-on-click="false" width-request="60">
	<variable>DATE_YEAR</variable>
	<input file>/tmp/.tzset_date_year</input>
	<default>'`echo $cur_date_year`'</default>
	<action signal="changed">echo new date_year is $DATE_YEAR >> $TZSET/dump</action>
	<action signal="changed">enable:TAPPLY</action>
    </comboboxtext> 
    
    <vbox width-request="30">
    <entry editable="true" fs-title="Enter the Hour" height-request="28">
    <variable>DATE_HOUR</variable>
    <default>'`echo $cur_date_hour`'</default>
	<action signal="changed">echo new date_hour is $DATE_HOUR >> $TZSET/dump</action>
    <action signal="changed">enable:TAPPLY</action>
	</entry>
	</vbox>
	
	<text use-markup="true" selectable="true" can-focus="no">
    <label>":"</label></text>

	
	<vbox width-request="30">
	<entry editable="true" fs-title="Enter the Minute" height-request="28">
    <variable>DATE_MINUTE</variable>
    <default>'`echo $cur_date_minute`'</default>
	<action signal="changed">echo new date_minute is $DATE_MINUTE >> $TZSET/dump</action>
    <action signal="changed">enable:TAPPLY</action>
	</entry>
    </vbox>
     
    <text use-markup="true" selectable="true" can-focus="no" width-request="175">
    <label>""</label></text>
    
     </hbox>
    </frame>
     <hbox>
        <button tooltip-text="Return to Previous Page">
		<label>Back</label>
		<input file stock="gtk-go-back"></input>
		<action>echo 0 > '$PAGELOCK'</action>
		<action>refresh:nbkMain</action>
		</button>
    
    	<button tooltip-text="Set the system clock to the entered time">
    	<variable>TAPPLY</variable>
		<sensitive>disabled</sensitive>
		<label>Apply</label>
		<input file stock="gtk-apply"></input>
        <action type="function">apply_new_time</action>
        <action>disable:TAPPLY</action>
        </button>
    
        <button cancel>
        </button>
  </hbox>

</vbox>





<vbox>
    <frame Localtime or UTC/GMT?>
      <hbox>
      <text xalign="0" wrap="true" width-request="590"><label>"
Please select below whether your system clock is set to localtime or if it is set to UTC time.  If your system is set to localtime, it should already be displaying the proper time in your panel.
      
If your system is showing the incorrect hour, then it is likely set to UTC.  If that is the case, then you should select UTC below and then choose your timezone from the dropdown list.
      
Note that you cannot select localtime and choose a timezone, as this is generally not needed in Porteus and it may alter your system time at the BIOS level.  If you want to set your system to localtime and select a timezone, please run the timeconfig utility inside a terminal.
"</label>        
      </text>
      </hbox>
      
      <hseparator></hseparator>
  <hbox>
  <vbox>
<radiobutton>
	<label>My system clock is set to localtime.</label>
	<default>'`echo $localtf`'</default>
	<variable>rbtlocal</variable>
	<action>if true echo system clock is localtime >> $TZSET/dump</action>
	<action>if true disable:TIMEZONE</action>
	<action>if true enable:OKBUT</action>
	<action>find_new_timezone</action>
	<action>refresh:current_timezone</action>
</radiobutton>
<radiobutton>
	<label>My system clock is set to UTC/GMT.</label>
	<default>'`echo $utctf`'</default>
	<variable>rbtutc</variable>
	<action>if true echo system clock is utc >> $TZSET/dump</action>
	<action>if true enable:TIMEZONE</action>
	<action>if true enable:OKBUT</action>
	<action>find_new_timezone</action>
	<action>refresh:current_timezone</action>
</radiobutton>
<hbox>
  <text use-markup="true" xalign="0" wrap="true"><label>"Timezone:"</label></text>
<comboboxtext focus-on-click="false" width-request="175">
	<variable>TIMEZONE</variable>
	<sensitive>'`echo $combo_sens`'</sensitive>
	<input file>/tmp/.tzset_list</input>
	<default>'`echo $orig_tz`'</default>
	<action signal="changed">echo selected timezone is $TIMEZONE >> $TZSET/dump</action>
	<action signal="changed">enable:OKBUT</action>
	<action signal="changed">find_new_timezone</action>
	<action signal="changed">refresh:current_timezone</action>
</comboboxtext>
</hbox>    
    </vbox>
    <vbox>
    <text width-request="15"><label>""</label></text>
    </vbox>
    <vseparator></vseparator>
    <vbox>
    <text width-request="15"><label>""</label></text>
    </vbox>
    <vbox>
    <hbox>
<text use-markup="true" xalign="0" wrap="true" width-request="270"><label>"If you click OK to apply these settings, your clock will now display the time as:
"</label></text>
    </hbox>
    <hbox>
      <text xalign="0"><label>"Display:"</label>
        <variable>current_timezone</variable>
        <input file>'$TZSET'/timenow</input></text>
     </hbox>
  </vbox>
  </hbox>
    </frame>
  <hbox>
  
        <button tooltip-text="Return to Previous Page">
		<label>Back</label>
		<input file stock="gtk-go-back"></input>
		<action>echo 0 > '$PAGELOCK'</action>
		<action>refresh:nbkMain</action>
		</button>
  
        <button tooltip-text="Apply these settings to your live system">
    	<variable>OKBUT</variable>
		<sensitive>disabled</sensitive>
		<label>Apply</label>
		<input file stock="gtk-apply"></input>
        <action type="function">set_utc_tz</action>
        <action>disable:OKBUT</action>
        </button>
    
    
    <button cancel>
    </button>
    
  </hbox>
</vbox>
  
  
<variable>nbkMain</variable>
<input file>"'$PAGELOCK'"</input>
</notebook>

</vbox>
<action signal="hide">exit:Cancel</action>
</window>
'
gtkdialog -p TIMECONFIG > $TZSET/gtk_dump

## Did user cancel ?
[ `egrep -o "Cancel|abort" $TZSET/gtk_dump` ] && rm -rf $TZSET && rm /tmp/.tzset* && exit


rm -rf $TZSET
rm /tmp/.tzset*

