#!/bin/bash
## A simple script to make a full screen screenshot, primarily for a barebones openbox/wm setup.
## for notification support, add dunst.
## 003-DE modules provide more featureful screenshot utilities. 
## by ncmprhnsbl forum.porteus.org

PATH=$PATH:/usr/share/porteus
# simple time/date name in jpg format
shot=$(date +%Y-%m-%d-%T).jpg
# use "xdg-user-dir PICTURES" as target directory
shotdir=$(xdg-user-dir PICTURES)
# use imlib2_grab to save to ~/Pictures
imlib2_grab ${shotdir}/${shot}
# if dunst is present, send a notification message, else use gtkdialog.py
if [ -e /usr/bin/dunst ]; then
	notify-send "${shot} saved to ${shotdir}"
elif [ -e /usr/share/porteus/gtkdialog.py ]; then
	gtkdialog.py -p "Screenshot:" -s "${shot} saved to ${shotdir}" -t 4000 
fi
