#!/bin/bash

NUM_MODULES=$(ls -1 "/mnt/live/memory/images/" | wc -l)
echo "<openbox_pipe_menu>"
echo "<item label=\"Modules Activated: $NUM_MODULES\"/>"
echo "<separator/>"
for MODULE in $(ls -1 "/mnt/live/memory/images/"); do
  echo "<item label=\""$MODULE"\"/>"
done
echo "</openbox_pipe_menu>"