#!/bin/bash
cat <<EOFMENU
<?xml version="1.0" encoding="UTF-8"?>
<openbox_pipe_menu>
<menu id="client-list-menu" />
<separator/>
<menu id="modpipe" />
<separator/>
<menu id="date-menu" />
<separator/>
<menu id="sysinfo-menu" />
<separator/>
<item label="Edit Autostart"> <action name="Execute">              
<execute>/opt/porteus-scripts/xorg/editor ~/.config/openbox/autostart</execute>
<startupnotify><enabled>yes</enabled></startupnotify>
</action></item>
<item label="Edit Menu"> <action name="Execute">              
<execute>psu "/opt/porteus-scripts/xorg/editor /opt/porteus-scripts/extra/pipemenus/menu4"</execute>
<startupnotify><enabled>yes</enabled></startupnotify>
</action></item>
<item label="Edit Keybinds etc"> <action name="Execute">              
<execute>/opt/porteus-scripts/xorg/editor ~/.config/openbox/rc.xml</execute>
<startupnotify><enabled>yes</enabled></startupnotify>
</action></item>
<item label="Keybinds Reference"> <action name="Execute">              
<execute>/opt/porteus-scripts/xorg/editor ~/.config/openbox/keyref1</execute>
<startupnotify><enabled>yes</enabled></startupnotify>
</action></item>
<separator/>
<item label="Reconfigure"> <action name="Reconfigure"/> </item>
<item label="Restart"> <action name="Restart"/> </item>
</openbox_pipe_menu>
EOFMENU
