'\" t
.\"     Title: udisksd
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: March 2013
.\"    Manual: System Daemon
.\"    Source: udisks 2.1.3
.\"  Language: English
.\"
.TH "UDISKSD" "8" "March 2013" "udisks 2\&.1\&.3" "System Daemon"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
udisksd \- The udisks system daemon
.SH "SYNOPSIS"
.HP \w'\fBudisksd\fR\ 'u
\fBudisksd\fR [\fB\-\-help\fR] [\fB\-\-replace\fR] [\fB\-\-no\-debug\fR] [\fB\-\-no\-sigint\fR]
.SH "DESCRIPTION"
.PP
The
\fBudisksd\fR
program provides the
\fIorg\&.freedesktop\&.UDisks2\fR
name on the system message bus\&. Users or administrators should never need to start this daemon as it will be automatically started by
\fBdbus-daemon\fR(1)
or
\fBsystemd\fR(1)
whenever an application tries to access its D\-Bus interfaces\&.
.PP
See the
\fBudisks\fR(8)
man page for more information\&.
.SH "OPTIONS"
.PP
\fB\-\-help\fR
.RS 4
Show help options\&.
.RE
.PP
\fB\-\-replace\fR
.RS 4
Replace existing daemon\&.
.RE
.PP
\fB\-\-no\-debug\fR
.RS 4
Do not print debug or informational messages on stdout/stderr\&.
.RE
.PP
\fB\-\-no\-sigint\fR
.RS 4
Do not handle SIGINT for controlled shutdown\&.
.RE
.SH "AUTHOR"
.PP
Written by David Zeuthen
<zeuthen@gmail\&.com>
with a lot of help from many others\&.
.SH "BUGS"
.PP
Please send bug reports to either the distribution bug tracker or the upstream bug tracker at
\m[blue]\fB\%https://bugs.freedesktop.org/enter_bug.cgi?product=udisks\fR\m[]\&.
.SH "SEE ALSO"
.PP
\fBudisks\fR(8),
\fBudisksctl\fR(1),
\fBpolkit\fR(8),
\fBdbus-daemon\fR(1),
\fBsystemd\fR(1)
