#!/bin/bash
# This script is used to provide a GUI messages for 'aufs-insert' script.

BASE=`basename $1`

# If the module is already activated, suggest deactivation:
if cat /proc/mounts | cut -d" " -f2 | grep -q "/mnt/live/memory/images/$BASE"; then
    Xdialog --title "activation query" --yesno "$BASE:\nModule is already activated. Deactivate?" 0 0
    if [ $? -eq 0 ]; then /opt/porteus-scripts/xorg/xdeactivate $BASE; fi
    exit
fi

# 'Stale NFS' workaround:
cd /usr/share/applications

# Insert the module to live filesystem:
/opt/porteus-scripts/xorg/aufs-insert $1
err=$?

if [ $err -eq 1 ]; then
    Xdialog --title "activate error" --msgbox "$BASE: Module must end with .xzm" 0 0
    exit
elif [ $err -eq 2 ]; then
    Xdialog --title "activate error" --msgbox "Not in the live mode, can't continue. Try xzm2dir $1 /" 0 0
    exit
elif [ $err -eq 3 ]; then
    Xdialog --title "activate error" --msgbox "$BASE: This is not a valid module" 0 0
    exit
elif [ $err -eq 4 ]; then
    Xdialog --title "activate error" --msgbox "$BASE: Cannot read module data. Corrupted download?" 0 0
    exit
elif [ $err -eq 5 ]; then
    Xdialog --title "activate error" --msgbox "$BASE: Can't insert module to union" 0 0
    exit
else
    Xdialog --title "activate success" --no-close --no-buttons --infobox "Well done! $BASE: module activated successfully." 0 0 2000 &
fi

exit 0
