#!/bin/bash

# this script opens a box with some options to log out, suspend or halt
# the running system.  I wrote it for desktops that don't have this service
# already


. /usr/lib/librokenman

exec 2>/dev/null
     
## Variables
export GLO="/tmp/glo_$$"
export PIXMAPS=/usr/share/pixmaps/porteus
     
mkdir -p $GLO
     
## export functions to perform logout actions:

gtklogout_halt()
{
dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
}; export -f gtklogout_halt

gtklogout_reboot()
{
dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
}; export -f gtklogout_reboot

gtklogout_suspend()
{
dbus-send --system --print-reply --dest="org.freedesktop.UPower" /org/freedesktop/UPower org.freedesktop.UPower.Suspend
}; export -f gtklogout_suspend

gtklogout_logout()
{
openbox --exit &
}; export -f gtklogout_logout
     
GTKLOGOUT='
    <window window_position="1" decorated="false" skip_taskbar_hint="true" window_position="1" allow-shrink="true" width-request="220" height-request="375">
      <vbox margin="30">
        <vbox>
          <pixmap><height>128</height><width>128</width><input file icon="system-log-out"></input></pixmap>
        </vbox>
        <vbox>
          '$(txtcolor 100 darkred x-large bold "Log Out")'
        </vbox>
          '$(hsep)'
       
        <hbox>
            <button tooltip-text="Shut Down your system" width-request="140">
           <variable>HALT</variable>
          <label>Shut Down</label>
         <input file icon="system-shutdown"></input>
          <action type="function">gtklogout_halt</action>
         </button>
        </hbox>
       
        <hbox>
            <button tooltip-text="Restart your system" width-request="140">
           <variable>REBOOT</variable>
          <label>"   Reboot  "</label>
         <input file icon="system-reboot"></input>
          <action type="function">gtklogout_reboot</action>
         </button>
        </hbox>
       
        <hbox>
            <button tooltip-text="Put your system into a low power state" width-request="140">
           <variable>SUSPEND</variable>
          <label>" Suspend  "</label>
         <input file icon="system-suspend"></input>
          <action type="function">gtklogout_suspend</action>
         </button>
        </hbox>
       
        <hbox>
            <button tooltip-text="Log out of openbox" width-request="140">
           <variable>LOGOUT</variable>
          <label>"  Log out   "</label>
         <input file icon="exit"></input>
          <action type="function">gtklogout_logout</action>
         </button>
        </hbox>
       
        <hbox>
            <button tooltip-text="Cancel" width-request="140">
           <variable>CANCEL</variable>
          <label>"  Cancel    "</label>
         <input file icon="gtk-cancel"></input>
          <action>exit:Cancel</action>
         </button>
        </hbox>
       
      </vbox>
      <action signal="hide">exit:Cancel</action>
    </window>
    '
export GTKLOGOUT
gtkdialog -p GTKLOGOUT > /tmp/.glo_dump

## Did user cancel ?
[ `egrep -o "Cancel|abort" /tmp/.glo_dump` ] && rm -rf $GLO && rm /tmp/.glo_* && exit

rm -rf $GLO && rm /tmp/.glo_*

exit