#!/bin/bash

## This script will search for and use an installed file manager.

where() { which $1 2>/dev/null; }
fileman=`where pcmanfm || where pcmanfm-qt || where nemo || where thunar || where spacefm || where caja || where dolphin || where polo`

if [ -e "$fileman" ]; then
	$fileman $1
else
	xterm -e mc $1 &
fi
