#!/bin/bash

PID=$$

-about)
	export pfilesearch_about="
<window title=\"pfilesearch - about\" icon-name=\"gtk-find\">
 <vbox>
  <notebook labels=\"About|License|Credits\">
   <vbox>
    <pixmap icon_size=\"6\"><input file stock=\"gtk-find\"></input></pixmap>
    <text use-markup=\"true\"><label>\"<b>pfilesearch $VERSION - File finder</b>\"</label></text>
    <text use-markup=\"true\"><label>Sigmund Berglund, Copyright 2007-2011</label></text>
    <text><label>\"\"</label></text>
     <button>
      <label>\"http://www.murga-linux.com/puppy/viewtopic.php?t=15136\"</label>
      <action>$BROWSER http:\/\/www.murga-linux.com\/puppy\/viewtopic.php?t=15136</action>
     </button>
   </vbox>
   <vbox>
    <text use-markup=\"true\"><label>\"pfilesearch is released under the <b>GNU General Public License</b> (GPL). You have the right to use and modify this software in any way you like, so long as any derivative works remain under a GPL license.\"</label></text>
    <text use-markup=\"true\"><label>\"This program is distributed in the hope that it will be useful, but <b>WITHOUT ANY WARRANTY</b>. See the GNU General Public License homepage for more details.\"</label></text>
    <hbox>
     <button>
      <label>\"http://www.gnu.org/licenses/\"</label>
      <action>$BROWSER http:\/\/www.gnu.org\/licenses\/</action>
     </button>
    </hbox>
   </vbox>
   <vbox>
    <edit><default>\"Translators:
French - Jean-Jacques Moulinier (esmourguit)
German - Thorsten Köbe (aragon)
Greece - (The Hamsters)
Italian - Angelo Gemmi
Japanese - Shigekazu Satoh (himajin)
Norwegian - Sigmund Berglund (zigbert)
Russian -  Valeriy Danilin
Spanish - Jacob S. Preciado (Proudog)

Others:
Disciple for contribution and bugfixing.
klhrevolutionist for ideas, code support and help with config file
Trapster for sed syntax.
...and more\"</default></edit>
   </vbox>
  </notebook>
  <hbox>
   <button>
    <input file icon=\"gtk-apply\"></input>
    <label>$LOC_OK</label>
   </button>
  </hbox>
 </vbox>
</window>"
	$GTKDIALOG --program pfilesearch_about --center
	;;
esac
