#!/bin/bash

## Easily compile VirtualBox and VirtualBox Guest Additions
## Author: Hamza & Brokenman

# Switch to root
if [ `whoami` != "root" ]; then
    /opt/porteus-scripts/xorg/psu /opt/porteus-scripts/gtk-easy-build-start
    exit
fi

. /usr/lib/librokenman

ICON=virtualbox.png
PIXMAPS=/usr/share/pixmaps/porteus
link=http://ponce.cc/porteus/i486/testing/gtk-easy-build
trap cleanup SIGHUP SIGINT SIGTERM

cleanup(){
rm /tmp/.easychoice 2>/dev/null
rm /tmp/gtk-easy-build* 2>/dev/null
exit
}

btnNoTxt(){
if [ "$#" -eq 3 ]; then
echo '<button tooltip-text="'$1'"><input file>"'$PIXMAPS/$2'"</input><width>'$3'</width>'
	else
if [ "$#" -eq 4 ]; then
echo '<button tooltip-text="'$1'"><input file '$2'="'$3'"></input><width>'$4'</width>'
fi fi
}

export MAIN_DIALOG='
<window window_position="1" title="'$DRIVER'" image-name="/usr/share/pixmaps/porteus/'$ICON'" allow-shrink="false" width-request="500">
<vbox margin="10">
	<hbox>
		<pixmap>
			<input file>/usr/share/pixmaps/porteus/'$ICON'</input>
			<width>64</width>
		</pixmap>
		'`txtcolor 400 darkred x-large bold "  Porteus VirtualBox builder"`'
	</hbox>
	'`hsep`'
	'`txtmarkup 460 "This applications compiles VirtualBox locally on your own computer for optimum compatibility. You can choose a local file or download the required file from the internet. Development module will be required for compilation. If you do not have it you will be prompted to download appropriate xzm."`'
	'`blankline`'
	<frame>
	<hbox>
		'`txtmarkup 220 "Choose an option: "`'
		<comboboxtext active="6" focus-on-click="false" button-sensitivity="1">
			<variable>easychoice</variable>
			<item>VirtualBox</item>
			<item>VirtualBox Guest Additions</item>
		</comboboxtext>
	</hbox>
	'`blankline`'
	</frame>
		<hbox>
		'`butcancel`'
		'`butok`'
	</hbox>
</vbox>
</window>
'
gtkdialog -p MAIN_DIALOG > /tmp/.easychoice

[ `egrep "Cancel|abort" /tmp/.easychoice` ] && { cleanup; exit; }
[[ `grep easychoice /tmp/.easychoice 2>/dev/null|cut -d'"' -f2` == "" ]] &&  { cleanup; exit; }

answer=`grep easychoice /tmp/.easychoice|cut -d'"' -f2`

## Internet check
if (wget -q --force-html --inet4-only "$link" -P /tmp); then
  if [ ! `grep -o 404 /tmp/gtk-easy-build` ]; then
    echo ok
    url=1
      else
    rm /tmp/gtk-easy-build* 2>/dev/null
    unset url
  fi
fi
[ -z $url ] && { gtk_message "An internet connection was not found or the porteus server was not reachable. Exiting now." 450 gtk-dialog-warning; cleanup; }

case $answer in
VirtualBox )
sh /tmp/gtk-easy-build vbox
cleanup
;;
"VirtualBox Guest Additions" )
sh /tmp/gtk-easy-build vboxguest
cleanup
;;
esac

rm /tmp/.easychoice 2>/dev/null
