
%Module PyKF5.KItemViews

%ModuleHeaderCode
#pragma GCC visibility push(default)
%End

%Import QtWidgets/QtWidgetsmod.sip

%Include kcategorizedsortfilterproxymodel.sip
%Include kcategorizedview.sip
%Include kcategorydrawer.sip
%Include kextendableitemdelegate.sip
%Include kfilterproxysearchline.sip
%Include klistwidgetsearchline.sip
%Include ktreewidgetsearchline.sip
%Include ktreewidgetsearchlinewidget.sip
%Include kwidgetitemdelegate.sip
